// Code generated by mockery. DO NOT EDIT.

package mockmockservice

import mock "github.com/stretchr/testify/mock"

// mockConstructorTestingTNewFile is an autogenerated mock type for the mockConstructorTestingTNewFile type
type mockConstructorTestingTNewFile struct {
	mock.Mock
}

type mockConstructorTestingTNewFile_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConstructorTestingTNewFile) EXPECT() *mockConstructorTestingTNewFile_Expecter {
	return &mockConstructorTestingTNewFile_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: _a0
func (_m *mockConstructorTestingTNewFile) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// mockConstructorTestingTNewFile_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type mockConstructorTestingTNewFile_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - _a0 func()
func (_e *mockConstructorTestingTNewFile_Expecter) Cleanup(_a0 interface{}) *mockConstructorTestingTNewFile_Cleanup_Call {
	return &mockConstructorTestingTNewFile_Cleanup_Call{Call: _e.mock.On("Cleanup", _a0)}
}

func (_c *mockConstructorTestingTNewFile_Cleanup_Call) Run(run func(_a0 func())) *mockConstructorTestingTNewFile_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *mockConstructorTestingTNewFile_Cleanup_Call) Return() *mockConstructorTestingTNewFile_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewFile_Cleanup_Call) RunAndReturn(run func(func())) *mockConstructorTestingTNewFile_Cleanup_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *mockConstructorTestingTNewFile) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// mockConstructorTestingTNewFile_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type mockConstructorTestingTNewFile_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *mockConstructorTestingTNewFile_Expecter) Errorf(format interface{}, args ...interface{}) *mockConstructorTestingTNewFile_Errorf_Call {
	return &mockConstructorTestingTNewFile_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *mockConstructorTestingTNewFile_Errorf_Call) Run(run func(format string, args ...interface{})) *mockConstructorTestingTNewFile_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockConstructorTestingTNewFile_Errorf_Call) Return() *mockConstructorTestingTNewFile_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewFile_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *mockConstructorTestingTNewFile_Errorf_Call {
	_c.Run(run)
	return _c
}

// FailNow provides a mock function with no fields
func (_m *mockConstructorTestingTNewFile) FailNow() {
	_m.Called()
}

// mockConstructorTestingTNewFile_FailNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailNow'
type mockConstructorTestingTNewFile_FailNow_Call struct {
	*mock.Call
}

// FailNow is a helper method to define mock.On call
func (_e *mockConstructorTestingTNewFile_Expecter) FailNow() *mockConstructorTestingTNewFile_FailNow_Call {
	return &mockConstructorTestingTNewFile_FailNow_Call{Call: _e.mock.On("FailNow")}
}

func (_c *mockConstructorTestingTNewFile_FailNow_Call) Run(run func()) *mockConstructorTestingTNewFile_FailNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConstructorTestingTNewFile_FailNow_Call) Return() *mockConstructorTestingTNewFile_FailNow_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewFile_FailNow_Call) RunAndReturn(run func()) *mockConstructorTestingTNewFile_FailNow_Call {
	_c.Run(run)
	return _c
}

// Logf provides a mock function with given fields: format, args
func (_m *mockConstructorTestingTNewFile) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// mockConstructorTestingTNewFile_Logf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logf'
type mockConstructorTestingTNewFile_Logf_Call struct {
	*mock.Call
}

// Logf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *mockConstructorTestingTNewFile_Expecter) Logf(format interface{}, args ...interface{}) *mockConstructorTestingTNewFile_Logf_Call {
	return &mockConstructorTestingTNewFile_Logf_Call{Call: _e.mock.On("Logf",
		append([]interface{}{format}, args...)...)}
}

func (_c *mockConstructorTestingTNewFile_Logf_Call) Run(run func(format string, args ...interface{})) *mockConstructorTestingTNewFile_Logf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockConstructorTestingTNewFile_Logf_Call) Return() *mockConstructorTestingTNewFile_Logf_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewFile_Logf_Call) RunAndReturn(run func(string, ...interface{})) *mockConstructorTestingTNewFile_Logf_Call {
	_c.Run(run)
	return _c
}

// newMockConstructorTestingTNewFile creates a new instance of mockConstructorTestingTNewFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConstructorTestingTNewFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConstructorTestingTNewFile {
	mock := &mockConstructorTestingTNewFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
