with-expecter: True
resolve-type-alias: False
issue-845-fix: True
print: True
disable-version-string: True
packages:
  "./":
    config:
      recursive: True
      all: True
      mockname: "Mock{{ .InterfaceName }}"
      outpkg: "{{.PackageName}}"
      filename: "{{ .InterfaceName | snakecase }}_mock_test.go"
      dir: "{{.InterfaceDir}}"
