// Code generated by mockery. DO NOT EDIT.

package repository

import (
	context "context"

	connection "github.com/raoptimus/db-migrator.go/internal/infrastructure/dal/connection"

	mock "github.com/stretchr/testify/mock"

	sqlex "github.com/raoptimus/db-migrator.go/internal/infrastructure/sqlex"
)

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection struct {
	mock.Mock
}

type MockConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnection) EXPECT() *MockConnection_Expecter {
	return &MockConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockConnection) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConnection_Expecter) Close() *MockConnection_Close_Call {
	return &MockConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConnection_Close_Call) Run(run func()) *MockConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_Close_Call) Return(_a0 error) *MockConnection_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Close_Call) RunAndReturn(run func() error) *MockConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DSN provides a mock function with no fields
func (_m *MockConnection) DSN() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DSN")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConnection_DSN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DSN'
type MockConnection_DSN_Call struct {
	*mock.Call
}

// DSN is a helper method to define mock.On call
func (_e *MockConnection_Expecter) DSN() *MockConnection_DSN_Call {
	return &MockConnection_DSN_Call{Call: _e.mock.On("DSN")}
}

func (_c *MockConnection_DSN_Call) Run(run func()) *MockConnection_DSN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_DSN_Call) Return(_a0 string) *MockConnection_DSN_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_DSN_Call) RunAndReturn(run func() string) *MockConnection_DSN_Call {
	_c.Call.Return(run)
	return _c
}

// Driver provides a mock function with no fields
func (_m *MockConnection) Driver() connection.Driver {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Driver")
	}

	var r0 connection.Driver
	if rf, ok := ret.Get(0).(func() connection.Driver); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(connection.Driver)
	}

	return r0
}

// MockConnection_Driver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Driver'
type MockConnection_Driver_Call struct {
	*mock.Call
}

// Driver is a helper method to define mock.On call
func (_e *MockConnection_Expecter) Driver() *MockConnection_Driver_Call {
	return &MockConnection_Driver_Call{Call: _e.mock.On("Driver")}
}

func (_c *MockConnection_Driver_Call) Run(run func()) *MockConnection_Driver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_Driver_Call) Return(_a0 connection.Driver) *MockConnection_Driver_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Driver_Call) RunAndReturn(run func() connection.Driver) *MockConnection_Driver_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockConnection) ExecContext(ctx context.Context, query string, args ...any) (sqlex.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sqlex.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlex.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sqlex.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnection_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockConnection_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockConnection_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockConnection_ExecContext_Call {
	return &MockConnection_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockConnection_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockConnection_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockConnection_ExecContext_Call) Return(_a0 sqlex.Result, _a1 error) *MockConnection_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnection_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sqlex.Result, error)) *MockConnection_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockConnection) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnection_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockConnection_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockConnection_Expecter) Ping() *MockConnection_Ping_Call {
	return &MockConnection_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockConnection_Ping_Call) Run(run func()) *MockConnection_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_Ping_Call) Return(_a0 error) *MockConnection_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Ping_Call) RunAndReturn(run func() error) *MockConnection_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *MockConnection) QueryContext(ctx context.Context, query string, args ...any) (sqlex.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 sqlex.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlex.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sqlex.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnection_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockConnection_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockConnection_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockConnection_QueryContext_Call {
	return &MockConnection_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockConnection_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockConnection_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockConnection_QueryContext_Call) Return(_a0 sqlex.Rows, _a1 error) *MockConnection_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnection_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sqlex.Rows, error)) *MockConnection_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// Transaction provides a mock function with given fields: ctx, txFn
func (_m *MockConnection) Transaction(ctx context.Context, txFn func(context.Context) error) error {
	ret := _m.Called(ctx, txFn)

	if len(ret) == 0 {
		panic("no return value specified for Transaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, txFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnection_Transaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transaction'
type MockConnection_Transaction_Call struct {
	*mock.Call
}

// Transaction is a helper method to define mock.On call
//   - ctx context.Context
//   - txFn func(context.Context) error
func (_e *MockConnection_Expecter) Transaction(ctx interface{}, txFn interface{}) *MockConnection_Transaction_Call {
	return &MockConnection_Transaction_Call{Call: _e.mock.On("Transaction", ctx, txFn)}
}

func (_c *MockConnection_Transaction_Call) Run(run func(ctx context.Context, txFn func(context.Context) error)) *MockConnection_Transaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockConnection_Transaction_Call) Return(_a0 error) *MockConnection_Transaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Transaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockConnection_Transaction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnection creates a new instance of MockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnection {
	mock := &MockConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
