// Code generated by mockery. DO NOT EDIT.

package repository

import (
	connection "github.com/raoptimus/db-migrator.go/internal/infrastructure/dal/connection"
	mock "github.com/stretchr/testify/mock"

)

// MockFactory is an autogenerated mock type for the Factory type
type MockFactory struct {
	mock.Mock
}

type MockFactory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFactory) EXPECT() *MockFactory_Expecter {
	return &MockFactory_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: conn, options
func (_m *MockFactory) Create(conn Connection, options *Options) (Repository, error) {
	ret := _m.Called(conn, options)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 Repository
	var r1 error
	if rf, ok := ret.Get(0).(func(Connection, *Options) (Repository, error)); ok {
		return rf(conn, options)
	}
	if rf, ok := ret.Get(0).(func(Connection, *Options) Repository); ok {
		r0 = rf(conn, options)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Repository)
		}
	}

	if rf, ok := ret.Get(1).(func(Connection, *Options) error); ok {
		r1 = rf(conn, options)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFactory_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFactory_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - conn Connection
//   - options *Options
func (_e *MockFactory_Expecter) Create(conn interface{}, options interface{}) *MockFactory_Create_Call {
	return &MockFactory_Create_Call{Call: _e.mock.On("Create", conn, options)}
}

func (_c *MockFactory_Create_Call) Run(run func(conn Connection, options *Options)) *MockFactory_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Connection), args[1].(*Options))
	})
	return _c
}

func (_c *MockFactory_Create_Call) Return(_a0 Repository, _a1 error) *MockFactory_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFactory_Create_Call) RunAndReturn(run func(Connection, *Options) (Repository, error)) *MockFactory_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Supports provides a mock function with given fields: driver
func (_m *MockFactory) Supports(driver connection.Driver) bool {
	ret := _m.Called(driver)

	if len(ret) == 0 {
		panic("no return value specified for Supports")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(connection.Driver) bool); ok {
		r0 = rf(driver)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockFactory_Supports_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Supports'
type MockFactory_Supports_Call struct {
	*mock.Call
}

// Supports is a helper method to define mock.On call
//   - driver connection.Driver
func (_e *MockFactory_Expecter) Supports(driver interface{}) *MockFactory_Supports_Call {
	return &MockFactory_Supports_Call{Call: _e.mock.On("Supports", driver)}
}

func (_c *MockFactory_Supports_Call) Run(run func(driver connection.Driver)) *MockFactory_Supports_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(connection.Driver))
	})
	return _c
}

func (_c *MockFactory_Supports_Call) Return(_a0 bool) *MockFactory_Supports_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFactory_Supports_Call) RunAndReturn(run func(connection.Driver) bool) *MockFactory_Supports_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFactory creates a new instance of MockFactory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFactory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFactory {
	mock := &MockFactory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
