// Code generated by mockery. DO NOT EDIT.

package repository

import (
	context "context"

	ddl "github.com/raoptimus/db-migrator.go/internal/infrastructure/iceberg/ddl"
	mock "github.com/stretchr/testify/mock"
)

// MockIcebergCatalog is an autogenerated mock type for the IcebergCatalog type
type MockIcebergCatalog struct {
	mock.Mock
}

type MockIcebergCatalog_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIcebergCatalog) EXPECT() *MockIcebergCatalog_Expecter {
	return &MockIcebergCatalog_Expecter{mock: &_m.Mock}
}

// ApplySchemaChange provides a mock function with given fields: ctx, op
func (_m *MockIcebergCatalog) ApplySchemaChange(ctx context.Context, op ddl.Operation) error {
	ret := _m.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for ApplySchemaChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ddl.Operation) error); ok {
		r0 = rf(ctx, op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_ApplySchemaChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySchemaChange'
type MockIcebergCatalog_ApplySchemaChange_Call struct {
	*mock.Call
}

// ApplySchemaChange is a helper method to define mock.On call
//   - ctx context.Context
//   - op ddl.Operation
func (_e *MockIcebergCatalog_Expecter) ApplySchemaChange(ctx interface{}, op interface{}) *MockIcebergCatalog_ApplySchemaChange_Call {
	return &MockIcebergCatalog_ApplySchemaChange_Call{Call: _e.mock.On("ApplySchemaChange", ctx, op)}
}

func (_c *MockIcebergCatalog_ApplySchemaChange_Call) Run(run func(ctx context.Context, op ddl.Operation)) *MockIcebergCatalog_ApplySchemaChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ddl.Operation))
	})
	return _c
}

func (_c *MockIcebergCatalog_ApplySchemaChange_Call) Return(_a0 error) *MockIcebergCatalog_ApplySchemaChange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_ApplySchemaChange_Call) RunAndReturn(run func(context.Context, ddl.Operation) error) *MockIcebergCatalog_ApplySchemaChange_Call {
	_c.Call.Return(run)
	return _c
}

// ApplySpecChange provides a mock function with given fields: ctx, op
func (_m *MockIcebergCatalog) ApplySpecChange(ctx context.Context, op ddl.Operation) error {
	ret := _m.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for ApplySpecChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ddl.Operation) error); ok {
		r0 = rf(ctx, op)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_ApplySpecChange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySpecChange'
type MockIcebergCatalog_ApplySpecChange_Call struct {
	*mock.Call
}

// ApplySpecChange is a helper method to define mock.On call
//   - ctx context.Context
//   - op ddl.Operation
func (_e *MockIcebergCatalog_Expecter) ApplySpecChange(ctx interface{}, op interface{}) *MockIcebergCatalog_ApplySpecChange_Call {
	return &MockIcebergCatalog_ApplySpecChange_Call{Call: _e.mock.On("ApplySpecChange", ctx, op)}
}

func (_c *MockIcebergCatalog_ApplySpecChange_Call) Run(run func(ctx context.Context, op ddl.Operation)) *MockIcebergCatalog_ApplySpecChange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ddl.Operation))
	})
	return _c
}

func (_c *MockIcebergCatalog_ApplySpecChange_Call) Return(_a0 error) *MockIcebergCatalog_ApplySpecChange_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_ApplySpecChange_Call) RunAndReturn(run func(context.Context, ddl.Operation) error) *MockIcebergCatalog_ApplySpecChange_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockIcebergCatalog) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIcebergCatalog_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIcebergCatalog_Expecter) Close() *MockIcebergCatalog_Close_Call {
	return &MockIcebergCatalog_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIcebergCatalog_Close_Call) Run(run func()) *MockIcebergCatalog_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIcebergCatalog_Close_Call) Return(_a0 error) *MockIcebergCatalog_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_Close_Call) RunAndReturn(run func() error) *MockIcebergCatalog_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNamespace provides a mock function with given fields: ctx, ns, props
func (_m *MockIcebergCatalog) CreateNamespace(ctx context.Context, ns []string, props map[string]string) error {
	ret := _m.Called(ctx, ns, props)

	if len(ret) == 0 {
		panic("no return value specified for CreateNamespace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, map[string]string) error); ok {
		r0 = rf(ctx, ns, props)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_CreateNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNamespace'
type MockIcebergCatalog_CreateNamespace_Call struct {
	*mock.Call
}

// CreateNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - ns []string
//   - props map[string]string
func (_e *MockIcebergCatalog_Expecter) CreateNamespace(ctx interface{}, ns interface{}, props interface{}) *MockIcebergCatalog_CreateNamespace_Call {
	return &MockIcebergCatalog_CreateNamespace_Call{Call: _e.mock.On("CreateNamespace", ctx, ns, props)}
}

func (_c *MockIcebergCatalog_CreateNamespace_Call) Run(run func(ctx context.Context, ns []string, props map[string]string)) *MockIcebergCatalog_CreateNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].(map[string]string))
	})
	return _c
}

func (_c *MockIcebergCatalog_CreateNamespace_Call) Return(_a0 error) *MockIcebergCatalog_CreateNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_CreateNamespace_Call) RunAndReturn(run func(context.Context, []string, map[string]string) error) *MockIcebergCatalog_CreateNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTable provides a mock function with given fields: ctx, ident, spec
func (_m *MockIcebergCatalog) CreateTable(ctx context.Context, ident ddl.Ident, spec ddl.CreateTableSpec) error {
	ret := _m.Called(ctx, ident, spec)

	if len(ret) == 0 {
		panic("no return value specified for CreateTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ddl.Ident, ddl.CreateTableSpec) error); ok {
		r0 = rf(ctx, ident, spec)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_CreateTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTable'
type MockIcebergCatalog_CreateTable_Call struct {
	*mock.Call
}

// CreateTable is a helper method to define mock.On call
//   - ctx context.Context
//   - ident ddl.Ident
//   - spec ddl.CreateTableSpec
func (_e *MockIcebergCatalog_Expecter) CreateTable(ctx interface{}, ident interface{}, spec interface{}) *MockIcebergCatalog_CreateTable_Call {
	return &MockIcebergCatalog_CreateTable_Call{Call: _e.mock.On("CreateTable", ctx, ident, spec)}
}

func (_c *MockIcebergCatalog_CreateTable_Call) Run(run func(ctx context.Context, ident ddl.Ident, spec ddl.CreateTableSpec)) *MockIcebergCatalog_CreateTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ddl.Ident), args[2].(ddl.CreateTableSpec))
	})
	return _c
}

func (_c *MockIcebergCatalog_CreateTable_Call) Return(_a0 error) *MockIcebergCatalog_CreateTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_CreateTable_Call) RunAndReturn(run func(context.Context, ddl.Ident, ddl.CreateTableSpec) error) *MockIcebergCatalog_CreateTable_Call {
	_c.Call.Return(run)
	return _c
}

// DropNamespace provides a mock function with given fields: ctx, ns
func (_m *MockIcebergCatalog) DropNamespace(ctx context.Context, ns []string) error {
	ret := _m.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for DropNamespace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) error); ok {
		r0 = rf(ctx, ns)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_DropNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropNamespace'
type MockIcebergCatalog_DropNamespace_Call struct {
	*mock.Call
}

// DropNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - ns []string
func (_e *MockIcebergCatalog_Expecter) DropNamespace(ctx interface{}, ns interface{}) *MockIcebergCatalog_DropNamespace_Call {
	return &MockIcebergCatalog_DropNamespace_Call{Call: _e.mock.On("DropNamespace", ctx, ns)}
}

func (_c *MockIcebergCatalog_DropNamespace_Call) Run(run func(ctx context.Context, ns []string)) *MockIcebergCatalog_DropNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockIcebergCatalog_DropNamespace_Call) Return(_a0 error) *MockIcebergCatalog_DropNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_DropNamespace_Call) RunAndReturn(run func(context.Context, []string) error) *MockIcebergCatalog_DropNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// DropTable provides a mock function with given fields: ctx, ident
func (_m *MockIcebergCatalog) DropTable(ctx context.Context, ident ddl.Ident) error {
	ret := _m.Called(ctx, ident)

	if len(ret) == 0 {
		panic("no return value specified for DropTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ddl.Ident) error); ok {
		r0 = rf(ctx, ident)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_DropTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropTable'
type MockIcebergCatalog_DropTable_Call struct {
	*mock.Call
}

// DropTable is a helper method to define mock.On call
//   - ctx context.Context
//   - ident ddl.Ident
func (_e *MockIcebergCatalog_Expecter) DropTable(ctx interface{}, ident interface{}) *MockIcebergCatalog_DropTable_Call {
	return &MockIcebergCatalog_DropTable_Call{Call: _e.mock.On("DropTable", ctx, ident)}
}

func (_c *MockIcebergCatalog_DropTable_Call) Run(run func(ctx context.Context, ident ddl.Ident)) *MockIcebergCatalog_DropTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ddl.Ident))
	})
	return _c
}

func (_c *MockIcebergCatalog_DropTable_Call) Return(_a0 error) *MockIcebergCatalog_DropTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_DropTable_Call) RunAndReturn(run func(context.Context, ddl.Ident) error) *MockIcebergCatalog_DropTable_Call {
	_c.Call.Return(run)
	return _c
}

// LoadNamespaceProperties provides a mock function with given fields: ctx, ns
func (_m *MockIcebergCatalog) LoadNamespaceProperties(ctx context.Context, ns []string) (map[string]string, error) {
	ret := _m.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for LoadNamespaceProperties")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, error)); ok {
		return rf(ctx, ns)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = rf(ctx, ns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIcebergCatalog_LoadNamespaceProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadNamespaceProperties'
type MockIcebergCatalog_LoadNamespaceProperties_Call struct {
	*mock.Call
}

// LoadNamespaceProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - ns []string
func (_e *MockIcebergCatalog_Expecter) LoadNamespaceProperties(ctx interface{}, ns interface{}) *MockIcebergCatalog_LoadNamespaceProperties_Call {
	return &MockIcebergCatalog_LoadNamespaceProperties_Call{Call: _e.mock.On("LoadNamespaceProperties", ctx, ns)}
}

func (_c *MockIcebergCatalog_LoadNamespaceProperties_Call) Run(run func(ctx context.Context, ns []string)) *MockIcebergCatalog_LoadNamespaceProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockIcebergCatalog_LoadNamespaceProperties_Call) Return(_a0 map[string]string, _a1 error) *MockIcebergCatalog_LoadNamespaceProperties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIcebergCatalog_LoadNamespaceProperties_Call) RunAndReturn(run func(context.Context, []string) (map[string]string, error)) *MockIcebergCatalog_LoadNamespaceProperties_Call {
	_c.Call.Return(run)
	return _c
}

// NamespaceExists provides a mock function with given fields: ctx, ns
func (_m *MockIcebergCatalog) NamespaceExists(ctx context.Context, ns []string) (bool, error) {
	ret := _m.Called(ctx, ns)

	if len(ret) == 0 {
		panic("no return value specified for NamespaceExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (bool, error)); ok {
		return rf(ctx, ns)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) bool); ok {
		r0 = rf(ctx, ns)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ns)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIcebergCatalog_NamespaceExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NamespaceExists'
type MockIcebergCatalog_NamespaceExists_Call struct {
	*mock.Call
}

// NamespaceExists is a helper method to define mock.On call
//   - ctx context.Context
//   - ns []string
func (_e *MockIcebergCatalog_Expecter) NamespaceExists(ctx interface{}, ns interface{}) *MockIcebergCatalog_NamespaceExists_Call {
	return &MockIcebergCatalog_NamespaceExists_Call{Call: _e.mock.On("NamespaceExists", ctx, ns)}
}

func (_c *MockIcebergCatalog_NamespaceExists_Call) Run(run func(ctx context.Context, ns []string)) *MockIcebergCatalog_NamespaceExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockIcebergCatalog_NamespaceExists_Call) Return(_a0 bool, _a1 error) *MockIcebergCatalog_NamespaceExists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIcebergCatalog_NamespaceExists_Call) RunAndReturn(run func(context.Context, []string) (bool, error)) *MockIcebergCatalog_NamespaceExists_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockIcebergCatalog) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockIcebergCatalog_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIcebergCatalog_Expecter) Ping(ctx interface{}) *MockIcebergCatalog_Ping_Call {
	return &MockIcebergCatalog_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockIcebergCatalog_Ping_Call) Run(run func(ctx context.Context)) *MockIcebergCatalog_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIcebergCatalog_Ping_Call) Return(_a0 error) *MockIcebergCatalog_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_Ping_Call) RunAndReturn(run func(context.Context) error) *MockIcebergCatalog_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// RenameTable provides a mock function with given fields: ctx, from, to
func (_m *MockIcebergCatalog) RenameTable(ctx context.Context, from ddl.Ident, to ddl.Ident) error {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for RenameTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ddl.Ident, ddl.Ident) error); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_RenameTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameTable'
type MockIcebergCatalog_RenameTable_Call struct {
	*mock.Call
}

// RenameTable is a helper method to define mock.On call
//   - ctx context.Context
//   - from ddl.Ident
//   - to ddl.Ident
func (_e *MockIcebergCatalog_Expecter) RenameTable(ctx interface{}, from interface{}, to interface{}) *MockIcebergCatalog_RenameTable_Call {
	return &MockIcebergCatalog_RenameTable_Call{Call: _e.mock.On("RenameTable", ctx, from, to)}
}

func (_c *MockIcebergCatalog_RenameTable_Call) Run(run func(ctx context.Context, from ddl.Ident, to ddl.Ident)) *MockIcebergCatalog_RenameTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(ddl.Ident), args[2].(ddl.Ident))
	})
	return _c
}

func (_c *MockIcebergCatalog_RenameTable_Call) Return(_a0 error) *MockIcebergCatalog_RenameTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_RenameTable_Call) RunAndReturn(run func(context.Context, ddl.Ident, ddl.Ident) error) *MockIcebergCatalog_RenameTable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateNamespaceProperties provides a mock function with given fields: ctx, ns, removals, updates
func (_m *MockIcebergCatalog) UpdateNamespaceProperties(ctx context.Context, ns []string, removals []string, updates map[string]string) error {
	ret := _m.Called(ctx, ns, removals, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateNamespaceProperties")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string, map[string]string) error); ok {
		r0 = rf(ctx, ns, removals, updates)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockIcebergCatalog_UpdateNamespaceProperties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateNamespaceProperties'
type MockIcebergCatalog_UpdateNamespaceProperties_Call struct {
	*mock.Call
}

// UpdateNamespaceProperties is a helper method to define mock.On call
//   - ctx context.Context
//   - ns []string
//   - removals []string
//   - updates map[string]string
func (_e *MockIcebergCatalog_Expecter) UpdateNamespaceProperties(ctx interface{}, ns interface{}, removals interface{}, updates interface{}) *MockIcebergCatalog_UpdateNamespaceProperties_Call {
	return &MockIcebergCatalog_UpdateNamespaceProperties_Call{Call: _e.mock.On("UpdateNamespaceProperties", ctx, ns, removals, updates)}
}

func (_c *MockIcebergCatalog_UpdateNamespaceProperties_Call) Run(run func(ctx context.Context, ns []string, removals []string, updates map[string]string)) *MockIcebergCatalog_UpdateNamespaceProperties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string), args[2].([]string), args[3].(map[string]string))
	})
	return _c
}

func (_c *MockIcebergCatalog_UpdateNamespaceProperties_Call) Return(_a0 error) *MockIcebergCatalog_UpdateNamespaceProperties_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_UpdateNamespaceProperties_Call) RunAndReturn(run func(context.Context, []string, []string, map[string]string) error) *MockIcebergCatalog_UpdateNamespaceProperties_Call {
	_c.Call.Return(run)
	return _c
}

// Warehouse provides a mock function with no fields
func (_m *MockIcebergCatalog) Warehouse() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Warehouse")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockIcebergCatalog_Warehouse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warehouse'
type MockIcebergCatalog_Warehouse_Call struct {
	*mock.Call
}

// Warehouse is a helper method to define mock.On call
func (_e *MockIcebergCatalog_Expecter) Warehouse() *MockIcebergCatalog_Warehouse_Call {
	return &MockIcebergCatalog_Warehouse_Call{Call: _e.mock.On("Warehouse")}
}

func (_c *MockIcebergCatalog_Warehouse_Call) Run(run func()) *MockIcebergCatalog_Warehouse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIcebergCatalog_Warehouse_Call) Return(_a0 string) *MockIcebergCatalog_Warehouse_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIcebergCatalog_Warehouse_Call) RunAndReturn(run func() string) *MockIcebergCatalog_Warehouse_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIcebergCatalog creates a new instance of MockIcebergCatalog. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIcebergCatalog(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIcebergCatalog {
	mock := &MockIcebergCatalog{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
