// Code generated by mockery. DO NOT EDIT.

package log

import mock "github.com/stretchr/testify/mock"

// MockcolorFunc is an autogenerated mock type for the colorFunc type
type MockcolorFunc struct {
	mock.Mock
}

type MockcolorFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockcolorFunc) EXPECT() *MockcolorFunc_Expecter {
	return &MockcolorFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: a
func (_m *MockcolorFunc) Execute(a ...any) string {
	var _ca []interface{}
	_ca = append(_ca, a...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(...any) string); ok {
		r0 = rf(a...)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockcolorFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockcolorFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - a ...any
func (_e *MockcolorFunc_Expecter) Execute(a ...interface{}) *MockcolorFunc_Execute_Call {
	return &MockcolorFunc_Execute_Call{Call: _e.mock.On("Execute",
		append([]interface{}{}, a...)...)}
}

func (_c *MockcolorFunc_Execute_Call) Run(run func(a ...any)) *MockcolorFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockcolorFunc_Execute_Call) Return(_a0 string) *MockcolorFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockcolorFunc_Execute_Call) RunAndReturn(run func(...any) string) *MockcolorFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockcolorFunc creates a new instance of MockcolorFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockcolorFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockcolorFunc {
	mock := &MockcolorFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
