// Code generated by mockery. DO NOT EDIT.

package tarantool

import (
	mock "github.com/stretchr/testify/mock"

	v2 "github.com/tarantool/go-tarantool/v2"
)

// MockConnection is an autogenerated mock type for the Connection type
type MockConnection struct {
	mock.Mock
}

type MockConnection_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConnection) EXPECT() *MockConnection_Expecter {
	return &MockConnection_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockConnection) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConnection_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockConnection_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockConnection_Expecter) Close() *MockConnection_Close_Call {
	return &MockConnection_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockConnection_Close_Call) Run(run func()) *MockConnection_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_Close_Call) Return(_a0 error) *MockConnection_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Close_Call) RunAndReturn(run func() error) *MockConnection_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function with given fields: req
func (_m *MockConnection) Do(req v2.Request) *v2.Future {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *v2.Future
	if rf, ok := ret.Get(0).(func(v2.Request) *v2.Future); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Future)
		}
	}

	return r0
}

// MockConnection_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockConnection_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req v2.Request
func (_e *MockConnection_Expecter) Do(req interface{}) *MockConnection_Do_Call {
	return &MockConnection_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockConnection_Do_Call) Run(run func(req v2.Request)) *MockConnection_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(v2.Request))
	})
	return _c
}

func (_c *MockConnection_Do_Call) Return(_a0 *v2.Future) *MockConnection_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConnection_Do_Call) RunAndReturn(run func(v2.Request) *v2.Future) *MockConnection_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewStream provides a mock function with no fields
func (_m *MockConnection) NewStream() (*v2.Stream, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewStream")
	}

	var r0 *v2.Stream
	var r1 error
	if rf, ok := ret.Get(0).(func() (*v2.Stream, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *v2.Stream); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v2.Stream)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConnection_NewStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewStream'
type MockConnection_NewStream_Call struct {
	*mock.Call
}

// NewStream is a helper method to define mock.On call
func (_e *MockConnection_Expecter) NewStream() *MockConnection_NewStream_Call {
	return &MockConnection_NewStream_Call{Call: _e.mock.On("NewStream")}
}

func (_c *MockConnection_NewStream_Call) Run(run func()) *MockConnection_NewStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConnection_NewStream_Call) Return(_a0 *v2.Stream, _a1 error) *MockConnection_NewStream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConnection_NewStream_Call) RunAndReturn(run func() (*v2.Stream, error)) *MockConnection_NewStream_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConnection creates a new instance of MockConnection. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConnection(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConnection {
	mock := &MockConnection{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
