// Code generated by mockery. DO NOT EDIT.

package tarantool

import (
	mock "github.com/stretchr/testify/mock"

	tarantool "github.com/tarantool/go-tarantool/v2"
)

// MockDoer is an autogenerated mock type for the Doer type
type MockDoer struct {
	mock.Mock
}

type MockDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoer) EXPECT() *MockDoer_Expecter {
	return &MockDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: req
func (_m *MockDoer) Do(req tarantool.Request) *tarantool.Future {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *tarantool.Future
	if rf, ok := ret.Get(0).(func(tarantool.Request) *tarantool.Future); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}

	return r0
}

// MockDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req tarantool.Request
func (_e *MockDoer_Expecter) Do(req interface{}) *MockDoer_Do_Call {
	return &MockDoer_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockDoer_Do_Call) Run(run func(req tarantool.Request)) *MockDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tarantool.Request))
	})
	return _c
}

func (_c *MockDoer_Do_Call) Return(_a0 *tarantool.Future) *MockDoer_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDoer_Do_Call) RunAndReturn(run func(tarantool.Request) *tarantool.Future) *MockDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoer {
	mock := &MockDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
