// Code generated by mockery. DO NOT EDIT.

package tarantool

import (
	mock "github.com/stretchr/testify/mock"

	tarantool "github.com/tarantool/go-tarantool/v2"
)

// MockStreamDoer is an autogenerated mock type for the StreamDoer type
type MockStreamDoer struct {
	mock.Mock
}

type MockStreamDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamDoer) EXPECT() *MockStreamDoer_Expecter {
	return &MockStreamDoer_Expecter{mock: &_m.Mock}
}

// Conn provides a mock function with no fields
func (_m *MockStreamDoer) Conn() *tarantool.Connection {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Conn")
	}

	var r0 *tarantool.Connection
	if rf, ok := ret.Get(0).(func() *tarantool.Connection); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Connection)
		}
	}

	return r0
}

// MockStreamDoer_Conn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Conn'
type MockStreamDoer_Conn_Call struct {
	*mock.Call
}

// Conn is a helper method to define mock.On call
func (_e *MockStreamDoer_Expecter) Conn() *MockStreamDoer_Conn_Call {
	return &MockStreamDoer_Conn_Call{Call: _e.mock.On("Conn")}
}

func (_c *MockStreamDoer_Conn_Call) Run(run func()) *MockStreamDoer_Conn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamDoer_Conn_Call) Return(_a0 *tarantool.Connection) *MockStreamDoer_Conn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamDoer_Conn_Call) RunAndReturn(run func() *tarantool.Connection) *MockStreamDoer_Conn_Call {
	_c.Call.Return(run)
	return _c
}

// Do provides a mock function with given fields: req
func (_m *MockStreamDoer) Do(req tarantool.Request) *tarantool.Future {
	ret := _m.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *tarantool.Future
	if rf, ok := ret.Get(0).(func(tarantool.Request) *tarantool.Future); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tarantool.Future)
		}
	}

	return r0
}

// MockStreamDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockStreamDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - req tarantool.Request
func (_e *MockStreamDoer_Expecter) Do(req interface{}) *MockStreamDoer_Do_Call {
	return &MockStreamDoer_Do_Call{Call: _e.mock.On("Do", req)}
}

func (_c *MockStreamDoer_Do_Call) Run(run func(req tarantool.Request)) *MockStreamDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(tarantool.Request))
	})
	return _c
}

func (_c *MockStreamDoer_Do_Call) Return(_a0 *tarantool.Future) *MockStreamDoer_Do_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStreamDoer_Do_Call) RunAndReturn(run func(tarantool.Request) *tarantool.Future) *MockStreamDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStreamDoer creates a new instance of MockStreamDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamDoer {
	mock := &MockStreamDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
