// Code generated by mockery. DO NOT EDIT.

package handler

import mock "github.com/stretchr/testify/mock"

// MockArgs is an autogenerated mock type for the Args type
type MockArgs struct {
	mock.Mock
}

type MockArgs_Expecter struct {
	mock *mock.Mock
}

func (_m *MockArgs) EXPECT() *MockArgs_Expecter {
	return &MockArgs_Expecter{mock: &_m.Mock}
}

// First provides a mock function with no fields
func (_m *MockArgs) First() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for First")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockArgs_First_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'First'
type MockArgs_First_Call struct {
	*mock.Call
}

// First is a helper method to define mock.On call
func (_e *MockArgs_Expecter) First() *MockArgs_First_Call {
	return &MockArgs_First_Call{Call: _e.mock.On("First")}
}

func (_c *MockArgs_First_Call) Run(run func()) *MockArgs_First_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArgs_First_Call) Return(_a0 string) *MockArgs_First_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArgs_First_Call) RunAndReturn(run func() string) *MockArgs_First_Call {
	_c.Call.Return(run)
	return _c
}

// Present provides a mock function with no fields
func (_m *MockArgs) Present() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Present")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockArgs_Present_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Present'
type MockArgs_Present_Call struct {
	*mock.Call
}

// Present is a helper method to define mock.On call
func (_e *MockArgs_Expecter) Present() *MockArgs_Present_Call {
	return &MockArgs_Present_Call{Call: _e.mock.On("Present")}
}

func (_c *MockArgs_Present_Call) Run(run func()) *MockArgs_Present_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArgs_Present_Call) Return(_a0 bool) *MockArgs_Present_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArgs_Present_Call) RunAndReturn(run func() bool) *MockArgs_Present_Call {
	_c.Call.Return(run)
	return _c
}

// Slice provides a mock function with no fields
func (_m *MockArgs) Slice() []string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Slice")
	}

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}

// MockArgs_Slice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Slice'
type MockArgs_Slice_Call struct {
	*mock.Call
}

// Slice is a helper method to define mock.On call
func (_e *MockArgs_Expecter) Slice() *MockArgs_Slice_Call {
	return &MockArgs_Slice_Call{Call: _e.mock.On("Slice")}
}

func (_c *MockArgs_Slice_Call) Run(run func()) *MockArgs_Slice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockArgs_Slice_Call) Return(_a0 []string) *MockArgs_Slice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockArgs_Slice_Call) RunAndReturn(run func() []string) *MockArgs_Slice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockArgs creates a new instance of MockArgs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockArgs(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockArgs {
	mock := &MockArgs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
