// Code generated by mockery. DO NOT EDIT.

package handler

import mock "github.com/stretchr/testify/mock"

// MockFileNameBuilder is an autogenerated mock type for the FileNameBuilder type
type MockFileNameBuilder struct {
	mock.Mock
}

type MockFileNameBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileNameBuilder) EXPECT() *MockFileNameBuilder_Expecter {
	return &MockFileNameBuilder_Expecter{mock: &_m.Mock}
}

// Down provides a mock function with given fields: version, forceSafely
func (_m *MockFileNameBuilder) Down(version string, forceSafely bool) (string, bool) {
	ret := _m.Called(version, forceSafely)

	if len(ret) == 0 {
		panic("no return value specified for Down")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string, bool) (string, bool)); ok {
		return rf(version, forceSafely)
	}
	if rf, ok := ret.Get(0).(func(string, bool) string); ok {
		r0 = rf(version, forceSafely)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, bool) bool); ok {
		r1 = rf(version, forceSafely)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockFileNameBuilder_Down_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Down'
type MockFileNameBuilder_Down_Call struct {
	*mock.Call
}

// Down is a helper method to define mock.On call
//   - version string
//   - forceSafely bool
func (_e *MockFileNameBuilder_Expecter) Down(version interface{}, forceSafely interface{}) *MockFileNameBuilder_Down_Call {
	return &MockFileNameBuilder_Down_Call{Call: _e.mock.On("Down", version, forceSafely)}
}

func (_c *MockFileNameBuilder_Down_Call) Run(run func(version string, forceSafely bool)) *MockFileNameBuilder_Down_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockFileNameBuilder_Down_Call) Return(fname string, safely bool) *MockFileNameBuilder_Down_Call {
	_c.Call.Return(fname, safely)
	return _c
}

func (_c *MockFileNameBuilder_Down_Call) RunAndReturn(run func(string, bool) (string, bool)) *MockFileNameBuilder_Down_Call {
	_c.Call.Return(run)
	return _c
}

// Up provides a mock function with given fields: version, forceSafely
func (_m *MockFileNameBuilder) Up(version string, forceSafely bool) (string, bool) {
	ret := _m.Called(version, forceSafely)

	if len(ret) == 0 {
		panic("no return value specified for Up")
	}

	var r0 string
	var r1 bool
	if rf, ok := ret.Get(0).(func(string, bool) (string, bool)); ok {
		return rf(version, forceSafely)
	}
	if rf, ok := ret.Get(0).(func(string, bool) string); ok {
		r0 = rf(version, forceSafely)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, bool) bool); ok {
		r1 = rf(version, forceSafely)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockFileNameBuilder_Up_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Up'
type MockFileNameBuilder_Up_Call struct {
	*mock.Call
}

// Up is a helper method to define mock.On call
//   - version string
//   - forceSafely bool
func (_e *MockFileNameBuilder_Expecter) Up(version interface{}, forceSafely interface{}) *MockFileNameBuilder_Up_Call {
	return &MockFileNameBuilder_Up_Call{Call: _e.mock.On("Up", version, forceSafely)}
}

func (_c *MockFileNameBuilder_Up_Call) Run(run func(version string, forceSafely bool)) *MockFileNameBuilder_Up_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(bool))
	})
	return _c
}

func (_c *MockFileNameBuilder_Up_Call) Return(fname string, safely bool) *MockFileNameBuilder_Up_Call {
	_c.Call.Return(fname, safely)
	return _c
}

func (_c *MockFileNameBuilder_Up_Call) RunAndReturn(run func(string, bool) (string, bool)) *MockFileNameBuilder_Up_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileNameBuilder creates a new instance of MockFileNameBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileNameBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileNameBuilder {
	mock := &MockFileNameBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
