// Code generated by mockery. DO NOT EDIT.

package handler

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/raoptimus/db-migrator.go/internal/domain/model"
)

// MockMigrationService is an autogenerated mock type for the MigrationService type
type MockMigrationService struct {
	mock.Mock
}

type MockMigrationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMigrationService) EXPECT() *MockMigrationService_Expecter {
	return &MockMigrationService_Expecter{mock: &_m.Mock}
}

// ApplyFile provides a mock function with given fields: ctx, migration, fileName, safely
func (_m *MockMigrationService) ApplyFile(ctx context.Context, migration *model.Migration, fileName string, safely bool) error {
	ret := _m.Called(ctx, migration, fileName, safely)

	if len(ret) == 0 {
		panic("no return value specified for ApplyFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Migration, string, bool) error); ok {
		r0 = rf(ctx, migration, fileName, safely)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMigrationService_ApplyFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyFile'
type MockMigrationService_ApplyFile_Call struct {
	*mock.Call
}

// ApplyFile is a helper method to define mock.On call
//   - ctx context.Context
//   - migration *model.Migration
//   - fileName string
//   - safely bool
func (_e *MockMigrationService_Expecter) ApplyFile(ctx interface{}, migration interface{}, fileName interface{}, safely interface{}) *MockMigrationService_ApplyFile_Call {
	return &MockMigrationService_ApplyFile_Call{Call: _e.mock.On("ApplyFile", ctx, migration, fileName, safely)}
}

func (_c *MockMigrationService_ApplyFile_Call) Run(run func(ctx context.Context, migration *model.Migration, fileName string, safely bool)) *MockMigrationService_ApplyFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Migration), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockMigrationService_ApplyFile_Call) Return(_a0 error) *MockMigrationService_ApplyFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMigrationService_ApplyFile_Call) RunAndReturn(run func(context.Context, *model.Migration, string, bool) error) *MockMigrationService_ApplyFile_Call {
	_c.Call.Return(run)
	return _c
}

// ApplySQL provides a mock function with given fields: ctx, safely, version, upSQL
func (_m *MockMigrationService) ApplySQL(ctx context.Context, safely bool, version string, upSQL string) error {
	ret := _m.Called(ctx, safely, version, upSQL)

	if len(ret) == 0 {
		panic("no return value specified for ApplySQL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, string, string) error); ok {
		r0 = rf(ctx, safely, version, upSQL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMigrationService_ApplySQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySQL'
type MockMigrationService_ApplySQL_Call struct {
	*mock.Call
}

// ApplySQL is a helper method to define mock.On call
//   - ctx context.Context
//   - safely bool
//   - version string
//   - upSQL string
func (_e *MockMigrationService_Expecter) ApplySQL(ctx interface{}, safely interface{}, version interface{}, upSQL interface{}) *MockMigrationService_ApplySQL_Call {
	return &MockMigrationService_ApplySQL_Call{Call: _e.mock.On("ApplySQL", ctx, safely, version, upSQL)}
}

func (_c *MockMigrationService_ApplySQL_Call) Run(run func(ctx context.Context, safely bool, version string, upSQL string)) *MockMigrationService_ApplySQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockMigrationService_ApplySQL_Call) Return(_a0 error) *MockMigrationService_ApplySQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMigrationService_ApplySQL_Call) RunAndReturn(run func(context.Context, bool, string, string) error) *MockMigrationService_ApplySQL_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, version
func (_m *MockMigrationService) Exists(ctx context.Context, version string) (bool, error) {
	ret := _m.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, version)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMigrationService_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMigrationService_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockMigrationService_Expecter) Exists(ctx interface{}, version interface{}) *MockMigrationService_Exists_Call {
	return &MockMigrationService_Exists_Call{Call: _e.mock.On("Exists", ctx, version)}
}

func (_c *MockMigrationService_Exists_Call) Run(run func(ctx context.Context, version string)) *MockMigrationService_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMigrationService_Exists_Call) Return(_a0 bool, _a1 error) *MockMigrationService_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMigrationService_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockMigrationService_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Migrations provides a mock function with given fields: ctx, limit
func (_m *MockMigrationService) Migrations(ctx context.Context, limit int) (model.Migrations, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Migrations")
	}

	var r0 model.Migrations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (model.Migrations, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) model.Migrations); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Migrations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMigrationService_Migrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrations'
type MockMigrationService_Migrations_Call struct {
	*mock.Call
}

// Migrations is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockMigrationService_Expecter) Migrations(ctx interface{}, limit interface{}) *MockMigrationService_Migrations_Call {
	return &MockMigrationService_Migrations_Call{Call: _e.mock.On("Migrations", ctx, limit)}
}

func (_c *MockMigrationService_Migrations_Call) Run(run func(ctx context.Context, limit int)) *MockMigrationService_Migrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockMigrationService_Migrations_Call) Return(_a0 model.Migrations, _a1 error) *MockMigrationService_Migrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMigrationService_Migrations_Call) RunAndReturn(run func(context.Context, int) (model.Migrations, error)) *MockMigrationService_Migrations_Call {
	_c.Call.Return(run)
	return _c
}

// NewMigrations provides a mock function with given fields: ctx
func (_m *MockMigrationService) NewMigrations(ctx context.Context) (model.Migrations, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for NewMigrations")
	}

	var r0 model.Migrations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.Migrations, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.Migrations); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Migrations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMigrationService_NewMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewMigrations'
type MockMigrationService_NewMigrations_Call struct {
	*mock.Call
}

// NewMigrations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMigrationService_Expecter) NewMigrations(ctx interface{}) *MockMigrationService_NewMigrations_Call {
	return &MockMigrationService_NewMigrations_Call{Call: _e.mock.On("NewMigrations", ctx)}
}

func (_c *MockMigrationService_NewMigrations_Call) Run(run func(ctx context.Context)) *MockMigrationService_NewMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockMigrationService_NewMigrations_Call) Return(_a0 model.Migrations, _a1 error) *MockMigrationService_NewMigrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMigrationService_NewMigrations_Call) RunAndReturn(run func(context.Context) (model.Migrations, error)) *MockMigrationService_NewMigrations_Call {
	_c.Call.Return(run)
	return _c
}

// RevertFile provides a mock function with given fields: ctx, migration, fileName, safely
func (_m *MockMigrationService) RevertFile(ctx context.Context, migration *model.Migration, fileName string, safely bool) error {
	ret := _m.Called(ctx, migration, fileName, safely)

	if len(ret) == 0 {
		panic("no return value specified for RevertFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Migration, string, bool) error); ok {
		r0 = rf(ctx, migration, fileName, safely)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMigrationService_RevertFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevertFile'
type MockMigrationService_RevertFile_Call struct {
	*mock.Call
}

// RevertFile is a helper method to define mock.On call
//   - ctx context.Context
//   - migration *model.Migration
//   - fileName string
//   - safely bool
func (_e *MockMigrationService_Expecter) RevertFile(ctx interface{}, migration interface{}, fileName interface{}, safely interface{}) *MockMigrationService_RevertFile_Call {
	return &MockMigrationService_RevertFile_Call{Call: _e.mock.On("RevertFile", ctx, migration, fileName, safely)}
}

func (_c *MockMigrationService_RevertFile_Call) Run(run func(ctx context.Context, migration *model.Migration, fileName string, safely bool)) *MockMigrationService_RevertFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Migration), args[2].(string), args[3].(bool))
	})
	return _c
}

func (_c *MockMigrationService_RevertFile_Call) Return(_a0 error) *MockMigrationService_RevertFile_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMigrationService_RevertFile_Call) RunAndReturn(run func(context.Context, *model.Migration, string, bool) error) *MockMigrationService_RevertFile_Call {
	_c.Call.Return(run)
	return _c
}

// RevertSQL provides a mock function with given fields: ctx, safely, version, downSQL
func (_m *MockMigrationService) RevertSQL(ctx context.Context, safely bool, version string, downSQL string) error {
	ret := _m.Called(ctx, safely, version, downSQL)

	if len(ret) == 0 {
		panic("no return value specified for RevertSQL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, string, string) error); ok {
		r0 = rf(ctx, safely, version, downSQL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMigrationService_RevertSQL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevertSQL'
type MockMigrationService_RevertSQL_Call struct {
	*mock.Call
}

// RevertSQL is a helper method to define mock.On call
//   - ctx context.Context
//   - safely bool
//   - version string
//   - downSQL string
func (_e *MockMigrationService_Expecter) RevertSQL(ctx interface{}, safely interface{}, version interface{}, downSQL interface{}) *MockMigrationService_RevertSQL_Call {
	return &MockMigrationService_RevertSQL_Call{Call: _e.mock.On("RevertSQL", ctx, safely, version, downSQL)}
}

func (_c *MockMigrationService_RevertSQL_Call) Run(run func(ctx context.Context, safely bool, version string, downSQL string)) *MockMigrationService_RevertSQL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockMigrationService_RevertSQL_Call) Return(_a0 error) *MockMigrationService_RevertSQL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMigrationService_RevertSQL_Call) RunAndReturn(run func(context.Context, bool, string, string) error) *MockMigrationService_RevertSQL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMigrationService creates a new instance of MockMigrationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMigrationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMigrationService {
	mock := &MockMigrationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
