// Code generated by mockery. DO NOT EDIT.

package handler

import (
	model "github.com/raoptimus/db-migrator.go/internal/domain/model"
	mock "github.com/stretchr/testify/mock"
)

// MockPresenter is an autogenerated mock type for the Presenter type
type MockPresenter struct {
	mock.Mock
}

type MockPresenter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPresenter) EXPECT() *MockPresenter_Expecter {
	return &MockPresenter_Expecter{mock: &_m.Mock}
}

// AskDowngradeConfirmation provides a mock function with given fields: count
func (_m *MockPresenter) AskDowngradeConfirmation(count int) string {
	ret := _m.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for AskDowngradeConfirmation")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(count)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPresenter_AskDowngradeConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AskDowngradeConfirmation'
type MockPresenter_AskDowngradeConfirmation_Call struct {
	*mock.Call
}

// AskDowngradeConfirmation is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) AskDowngradeConfirmation(count interface{}) *MockPresenter_AskDowngradeConfirmation_Call {
	return &MockPresenter_AskDowngradeConfirmation_Call{Call: _e.mock.On("AskDowngradeConfirmation", count)}
}

func (_c *MockPresenter_AskDowngradeConfirmation_Call) Run(run func(count int)) *MockPresenter_AskDowngradeConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_AskDowngradeConfirmation_Call) Return(_a0 string) *MockPresenter_AskDowngradeConfirmation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenter_AskDowngradeConfirmation_Call) RunAndReturn(run func(int) string) *MockPresenter_AskDowngradeConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// AskRedoConfirmation provides a mock function with given fields: count
func (_m *MockPresenter) AskRedoConfirmation(count int) string {
	ret := _m.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for AskRedoConfirmation")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(count)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPresenter_AskRedoConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AskRedoConfirmation'
type MockPresenter_AskRedoConfirmation_Call struct {
	*mock.Call
}

// AskRedoConfirmation is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) AskRedoConfirmation(count interface{}) *MockPresenter_AskRedoConfirmation_Call {
	return &MockPresenter_AskRedoConfirmation_Call{Call: _e.mock.On("AskRedoConfirmation", count)}
}

func (_c *MockPresenter_AskRedoConfirmation_Call) Run(run func(count int)) *MockPresenter_AskRedoConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_AskRedoConfirmation_Call) Return(_a0 string) *MockPresenter_AskRedoConfirmation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenter_AskRedoConfirmation_Call) RunAndReturn(run func(int) string) *MockPresenter_AskRedoConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// AskUpgradeConfirmation provides a mock function with given fields: count
func (_m *MockPresenter) AskUpgradeConfirmation(count int) string {
	ret := _m.Called(count)

	if len(ret) == 0 {
		panic("no return value specified for AskUpgradeConfirmation")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(count)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockPresenter_AskUpgradeConfirmation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AskUpgradeConfirmation'
type MockPresenter_AskUpgradeConfirmation_Call struct {
	*mock.Call
}

// AskUpgradeConfirmation is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) AskUpgradeConfirmation(count interface{}) *MockPresenter_AskUpgradeConfirmation_Call {
	return &MockPresenter_AskUpgradeConfirmation_Call{Call: _e.mock.On("AskUpgradeConfirmation", count)}
}

func (_c *MockPresenter_AskUpgradeConfirmation_Call) Run(run func(count int)) *MockPresenter_AskUpgradeConfirmation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_AskUpgradeConfirmation_Call) Return(_a0 string) *MockPresenter_AskUpgradeConfirmation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPresenter_AskUpgradeConfirmation_Call) RunAndReturn(run func(int) string) *MockPresenter_AskUpgradeConfirmation_Call {
	_c.Call.Return(run)
	return _c
}

// PrintMigrations provides a mock function with given fields: migrations, withTime
func (_m *MockPresenter) PrintMigrations(migrations model.Migrations, withTime bool) {
	_m.Called(migrations, withTime)
}

// MockPresenter_PrintMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrintMigrations'
type MockPresenter_PrintMigrations_Call struct {
	*mock.Call
}

// PrintMigrations is a helper method to define mock.On call
//   - migrations model.Migrations
//   - withTime bool
func (_e *MockPresenter_Expecter) PrintMigrations(migrations interface{}, withTime interface{}) *MockPresenter_PrintMigrations_Call {
	return &MockPresenter_PrintMigrations_Call{Call: _e.mock.On("PrintMigrations", migrations, withTime)}
}

func (_c *MockPresenter_PrintMigrations_Call) Run(run func(migrations model.Migrations, withTime bool)) *MockPresenter_PrintMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Migrations), args[1].(bool))
	})
	return _c
}

func (_c *MockPresenter_PrintMigrations_Call) Return() *MockPresenter_PrintMigrations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_PrintMigrations_Call) RunAndReturn(run func(model.Migrations, bool)) *MockPresenter_PrintMigrations_Call {
	_c.Run(run)
	return _c
}

// ShowAllHistoryHeader provides a mock function with given fields: count
func (_m *MockPresenter) ShowAllHistoryHeader(count int) {
	_m.Called(count)
}

// MockPresenter_ShowAllHistoryHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowAllHistoryHeader'
type MockPresenter_ShowAllHistoryHeader_Call struct {
	*mock.Call
}

// ShowAllHistoryHeader is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) ShowAllHistoryHeader(count interface{}) *MockPresenter_ShowAllHistoryHeader_Call {
	return &MockPresenter_ShowAllHistoryHeader_Call{Call: _e.mock.On("ShowAllHistoryHeader", count)}
}

func (_c *MockPresenter_ShowAllHistoryHeader_Call) Run(run func(count int)) *MockPresenter_ShowAllHistoryHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowAllHistoryHeader_Call) Return() *MockPresenter_ShowAllHistoryHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowAllHistoryHeader_Call) RunAndReturn(run func(int)) *MockPresenter_ShowAllHistoryHeader_Call {
	_c.Run(run)
	return _c
}

// ShowDowngradeError provides a mock function with given fields: reverted, total
func (_m *MockPresenter) ShowDowngradeError(reverted int, total int) {
	_m.Called(reverted, total)
}

// MockPresenter_ShowDowngradeError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowDowngradeError'
type MockPresenter_ShowDowngradeError_Call struct {
	*mock.Call
}

// ShowDowngradeError is a helper method to define mock.On call
//   - reverted int
//   - total int
func (_e *MockPresenter_Expecter) ShowDowngradeError(reverted interface{}, total interface{}) *MockPresenter_ShowDowngradeError_Call {
	return &MockPresenter_ShowDowngradeError_Call{Call: _e.mock.On("ShowDowngradeError", reverted, total)}
}

func (_c *MockPresenter_ShowDowngradeError_Call) Run(run func(reverted int, total int)) *MockPresenter_ShowDowngradeError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowDowngradeError_Call) Return() *MockPresenter_ShowDowngradeError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowDowngradeError_Call) RunAndReturn(run func(int, int)) *MockPresenter_ShowDowngradeError_Call {
	_c.Run(run)
	return _c
}

// ShowDowngradePlan provides a mock function with given fields: migrations
func (_m *MockPresenter) ShowDowngradePlan(migrations model.Migrations) {
	_m.Called(migrations)
}

// MockPresenter_ShowDowngradePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowDowngradePlan'
type MockPresenter_ShowDowngradePlan_Call struct {
	*mock.Call
}

// ShowDowngradePlan is a helper method to define mock.On call
//   - migrations model.Migrations
func (_e *MockPresenter_Expecter) ShowDowngradePlan(migrations interface{}) *MockPresenter_ShowDowngradePlan_Call {
	return &MockPresenter_ShowDowngradePlan_Call{Call: _e.mock.On("ShowDowngradePlan", migrations)}
}

func (_c *MockPresenter_ShowDowngradePlan_Call) Run(run func(migrations model.Migrations)) *MockPresenter_ShowDowngradePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Migrations))
	})
	return _c
}

func (_c *MockPresenter_ShowDowngradePlan_Call) Return() *MockPresenter_ShowDowngradePlan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowDowngradePlan_Call) RunAndReturn(run func(model.Migrations)) *MockPresenter_ShowDowngradePlan_Call {
	_c.Run(run)
	return _c
}

// ShowDowngradeSuccess provides a mock function with given fields: count
func (_m *MockPresenter) ShowDowngradeSuccess(count int) {
	_m.Called(count)
}

// MockPresenter_ShowDowngradeSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowDowngradeSuccess'
type MockPresenter_ShowDowngradeSuccess_Call struct {
	*mock.Call
}

// ShowDowngradeSuccess is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) ShowDowngradeSuccess(count interface{}) *MockPresenter_ShowDowngradeSuccess_Call {
	return &MockPresenter_ShowDowngradeSuccess_Call{Call: _e.mock.On("ShowDowngradeSuccess", count)}
}

func (_c *MockPresenter_ShowDowngradeSuccess_Call) Run(run func(count int)) *MockPresenter_ShowDowngradeSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowDowngradeSuccess_Call) Return() *MockPresenter_ShowDowngradeSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowDowngradeSuccess_Call) RunAndReturn(run func(int)) *MockPresenter_ShowDowngradeSuccess_Call {
	_c.Run(run)
	return _c
}

// ShowHistoryHeader provides a mock function with given fields: count
func (_m *MockPresenter) ShowHistoryHeader(count int) {
	_m.Called(count)
}

// MockPresenter_ShowHistoryHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowHistoryHeader'
type MockPresenter_ShowHistoryHeader_Call struct {
	*mock.Call
}

// ShowHistoryHeader is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) ShowHistoryHeader(count interface{}) *MockPresenter_ShowHistoryHeader_Call {
	return &MockPresenter_ShowHistoryHeader_Call{Call: _e.mock.On("ShowHistoryHeader", count)}
}

func (_c *MockPresenter_ShowHistoryHeader_Call) Run(run func(count int)) *MockPresenter_ShowHistoryHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowHistoryHeader_Call) Return() *MockPresenter_ShowHistoryHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowHistoryHeader_Call) RunAndReturn(run func(int)) *MockPresenter_ShowHistoryHeader_Call {
	_c.Run(run)
	return _c
}

// ShowNewMigrationsHeader provides a mock function with given fields: count
func (_m *MockPresenter) ShowNewMigrationsHeader(count int) {
	_m.Called(count)
}

// MockPresenter_ShowNewMigrationsHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowNewMigrationsHeader'
type MockPresenter_ShowNewMigrationsHeader_Call struct {
	*mock.Call
}

// ShowNewMigrationsHeader is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) ShowNewMigrationsHeader(count interface{}) *MockPresenter_ShowNewMigrationsHeader_Call {
	return &MockPresenter_ShowNewMigrationsHeader_Call{Call: _e.mock.On("ShowNewMigrationsHeader", count)}
}

func (_c *MockPresenter_ShowNewMigrationsHeader_Call) Run(run func(count int)) *MockPresenter_ShowNewMigrationsHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowNewMigrationsHeader_Call) Return() *MockPresenter_ShowNewMigrationsHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowNewMigrationsHeader_Call) RunAndReturn(run func(int)) *MockPresenter_ShowNewMigrationsHeader_Call {
	_c.Run(run)
	return _c
}

// ShowNewMigrationsLimitedHeader provides a mock function with given fields: shown, total
func (_m *MockPresenter) ShowNewMigrationsLimitedHeader(shown int, total int) {
	_m.Called(shown, total)
}

// MockPresenter_ShowNewMigrationsLimitedHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowNewMigrationsLimitedHeader'
type MockPresenter_ShowNewMigrationsLimitedHeader_Call struct {
	*mock.Call
}

// ShowNewMigrationsLimitedHeader is a helper method to define mock.On call
//   - shown int
//   - total int
func (_e *MockPresenter_Expecter) ShowNewMigrationsLimitedHeader(shown interface{}, total interface{}) *MockPresenter_ShowNewMigrationsLimitedHeader_Call {
	return &MockPresenter_ShowNewMigrationsLimitedHeader_Call{Call: _e.mock.On("ShowNewMigrationsLimitedHeader", shown, total)}
}

func (_c *MockPresenter_ShowNewMigrationsLimitedHeader_Call) Run(run func(shown int, total int)) *MockPresenter_ShowNewMigrationsLimitedHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowNewMigrationsLimitedHeader_Call) Return() *MockPresenter_ShowNewMigrationsLimitedHeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowNewMigrationsLimitedHeader_Call) RunAndReturn(run func(int, int)) *MockPresenter_ShowNewMigrationsLimitedHeader_Call {
	_c.Run(run)
	return _c
}

// ShowNoMigrationsToRevert provides a mock function with no fields
func (_m *MockPresenter) ShowNoMigrationsToRevert() {
	_m.Called()
}

// MockPresenter_ShowNoMigrationsToRevert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowNoMigrationsToRevert'
type MockPresenter_ShowNoMigrationsToRevert_Call struct {
	*mock.Call
}

// ShowNoMigrationsToRevert is a helper method to define mock.On call
func (_e *MockPresenter_Expecter) ShowNoMigrationsToRevert() *MockPresenter_ShowNoMigrationsToRevert_Call {
	return &MockPresenter_ShowNoMigrationsToRevert_Call{Call: _e.mock.On("ShowNoMigrationsToRevert")}
}

func (_c *MockPresenter_ShowNoMigrationsToRevert_Call) Run(run func()) *MockPresenter_ShowNoMigrationsToRevert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPresenter_ShowNoMigrationsToRevert_Call) Return() *MockPresenter_ShowNoMigrationsToRevert_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowNoMigrationsToRevert_Call) RunAndReturn(run func()) *MockPresenter_ShowNoMigrationsToRevert_Call {
	_c.Run(run)
	return _c
}

// ShowNoNewMigrations provides a mock function with no fields
func (_m *MockPresenter) ShowNoNewMigrations() {
	_m.Called()
}

// MockPresenter_ShowNoNewMigrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowNoNewMigrations'
type MockPresenter_ShowNoNewMigrations_Call struct {
	*mock.Call
}

// ShowNoNewMigrations is a helper method to define mock.On call
func (_e *MockPresenter_Expecter) ShowNoNewMigrations() *MockPresenter_ShowNoNewMigrations_Call {
	return &MockPresenter_ShowNoNewMigrations_Call{Call: _e.mock.On("ShowNoNewMigrations")}
}

func (_c *MockPresenter_ShowNoNewMigrations_Call) Run(run func()) *MockPresenter_ShowNoNewMigrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPresenter_ShowNoNewMigrations_Call) Return() *MockPresenter_ShowNoNewMigrations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowNoNewMigrations_Call) RunAndReturn(run func()) *MockPresenter_ShowNoNewMigrations_Call {
	_c.Run(run)
	return _c
}

// ShowRedoError provides a mock function with no fields
func (_m *MockPresenter) ShowRedoError() {
	_m.Called()
}

// MockPresenter_ShowRedoError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowRedoError'
type MockPresenter_ShowRedoError_Call struct {
	*mock.Call
}

// ShowRedoError is a helper method to define mock.On call
func (_e *MockPresenter_Expecter) ShowRedoError() *MockPresenter_ShowRedoError_Call {
	return &MockPresenter_ShowRedoError_Call{Call: _e.mock.On("ShowRedoError")}
}

func (_c *MockPresenter_ShowRedoError_Call) Run(run func()) *MockPresenter_ShowRedoError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPresenter_ShowRedoError_Call) Return() *MockPresenter_ShowRedoError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowRedoError_Call) RunAndReturn(run func()) *MockPresenter_ShowRedoError_Call {
	_c.Run(run)
	return _c
}

// ShowRedoPlan provides a mock function with given fields: migrations
func (_m *MockPresenter) ShowRedoPlan(migrations model.Migrations) {
	_m.Called(migrations)
}

// MockPresenter_ShowRedoPlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowRedoPlan'
type MockPresenter_ShowRedoPlan_Call struct {
	*mock.Call
}

// ShowRedoPlan is a helper method to define mock.On call
//   - migrations model.Migrations
func (_e *MockPresenter_Expecter) ShowRedoPlan(migrations interface{}) *MockPresenter_ShowRedoPlan_Call {
	return &MockPresenter_ShowRedoPlan_Call{Call: _e.mock.On("ShowRedoPlan", migrations)}
}

func (_c *MockPresenter_ShowRedoPlan_Call) Run(run func(migrations model.Migrations)) *MockPresenter_ShowRedoPlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Migrations))
	})
	return _c
}

func (_c *MockPresenter_ShowRedoPlan_Call) Return() *MockPresenter_ShowRedoPlan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowRedoPlan_Call) RunAndReturn(run func(model.Migrations)) *MockPresenter_ShowRedoPlan_Call {
	_c.Run(run)
	return _c
}

// ShowRedoSuccess provides a mock function with given fields: count
func (_m *MockPresenter) ShowRedoSuccess(count int) {
	_m.Called(count)
}

// MockPresenter_ShowRedoSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowRedoSuccess'
type MockPresenter_ShowRedoSuccess_Call struct {
	*mock.Call
}

// ShowRedoSuccess is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) ShowRedoSuccess(count interface{}) *MockPresenter_ShowRedoSuccess_Call {
	return &MockPresenter_ShowRedoSuccess_Call{Call: _e.mock.On("ShowRedoSuccess", count)}
}

func (_c *MockPresenter_ShowRedoSuccess_Call) Run(run func(count int)) *MockPresenter_ShowRedoSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowRedoSuccess_Call) Return() *MockPresenter_ShowRedoSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowRedoSuccess_Call) RunAndReturn(run func(int)) *MockPresenter_ShowRedoSuccess_Call {
	_c.Run(run)
	return _c
}

// ShowUpgradeError provides a mock function with given fields: applied, total
func (_m *MockPresenter) ShowUpgradeError(applied int, total int) {
	_m.Called(applied, total)
}

// MockPresenter_ShowUpgradeError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowUpgradeError'
type MockPresenter_ShowUpgradeError_Call struct {
	*mock.Call
}

// ShowUpgradeError is a helper method to define mock.On call
//   - applied int
//   - total int
func (_e *MockPresenter_Expecter) ShowUpgradeError(applied interface{}, total interface{}) *MockPresenter_ShowUpgradeError_Call {
	return &MockPresenter_ShowUpgradeError_Call{Call: _e.mock.On("ShowUpgradeError", applied, total)}
}

func (_c *MockPresenter_ShowUpgradeError_Call) Run(run func(applied int, total int)) *MockPresenter_ShowUpgradeError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowUpgradeError_Call) Return() *MockPresenter_ShowUpgradeError_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowUpgradeError_Call) RunAndReturn(run func(int, int)) *MockPresenter_ShowUpgradeError_Call {
	_c.Run(run)
	return _c
}

// ShowUpgradePlan provides a mock function with given fields: migrations, total
func (_m *MockPresenter) ShowUpgradePlan(migrations model.Migrations, total int) {
	_m.Called(migrations, total)
}

// MockPresenter_ShowUpgradePlan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowUpgradePlan'
type MockPresenter_ShowUpgradePlan_Call struct {
	*mock.Call
}

// ShowUpgradePlan is a helper method to define mock.On call
//   - migrations model.Migrations
//   - total int
func (_e *MockPresenter_Expecter) ShowUpgradePlan(migrations interface{}, total interface{}) *MockPresenter_ShowUpgradePlan_Call {
	return &MockPresenter_ShowUpgradePlan_Call{Call: _e.mock.On("ShowUpgradePlan", migrations, total)}
}

func (_c *MockPresenter_ShowUpgradePlan_Call) Run(run func(migrations model.Migrations, total int)) *MockPresenter_ShowUpgradePlan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Migrations), args[1].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowUpgradePlan_Call) Return() *MockPresenter_ShowUpgradePlan_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowUpgradePlan_Call) RunAndReturn(run func(model.Migrations, int)) *MockPresenter_ShowUpgradePlan_Call {
	_c.Run(run)
	return _c
}

// ShowUpgradeSuccess provides a mock function with given fields: count
func (_m *MockPresenter) ShowUpgradeSuccess(count int) {
	_m.Called(count)
}

// MockPresenter_ShowUpgradeSuccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowUpgradeSuccess'
type MockPresenter_ShowUpgradeSuccess_Call struct {
	*mock.Call
}

// ShowUpgradeSuccess is a helper method to define mock.On call
//   - count int
func (_e *MockPresenter_Expecter) ShowUpgradeSuccess(count interface{}) *MockPresenter_ShowUpgradeSuccess_Call {
	return &MockPresenter_ShowUpgradeSuccess_Call{Call: _e.mock.On("ShowUpgradeSuccess", count)}
}

func (_c *MockPresenter_ShowUpgradeSuccess_Call) Run(run func(count int)) *MockPresenter_ShowUpgradeSuccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockPresenter_ShowUpgradeSuccess_Call) Return() *MockPresenter_ShowUpgradeSuccess_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPresenter_ShowUpgradeSuccess_Call) RunAndReturn(run func(int)) *MockPresenter_ShowUpgradeSuccess_Call {
	_c.Run(run)
	return _c
}

// NewMockPresenter creates a new instance of MockPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPresenter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPresenter {
	mock := &MockPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
