// Code generated by mockery. DO NOT EDIT.

package handler

import (
	mock "github.com/stretchr/testify/mock"
)

// MockServiceHandler is an autogenerated mock type for the ServiceHandler type
type MockServiceHandler struct {
	mock.Mock
}

type MockServiceHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceHandler) EXPECT() *MockServiceHandler_Expecter {
	return &MockServiceHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: cmd, svc
func (_m *MockServiceHandler) Handle(cmd *Command, svc MigrationService) error {
	ret := _m.Called(cmd, svc)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*Command, MigrationService) error); ok {
		r0 = rf(cmd, svc)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServiceHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockServiceHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - cmd *Command
//   - svc MigrationService
func (_e *MockServiceHandler_Expecter) Handle(cmd interface{}, svc interface{}) *MockServiceHandler_Handle_Call {
	return &MockServiceHandler_Handle_Call{Call: _e.mock.On("Handle", cmd, svc)}
}

func (_c *MockServiceHandler_Handle_Call) Run(run func(cmd *Command, svc MigrationService)) *MockServiceHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*Command), args[1].(MigrationService))
	})
	return _c
}

func (_c *MockServiceHandler_Handle_Call) Return(_a0 error) *MockServiceHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServiceHandler_Handle_Call) RunAndReturn(run func(*Command, MigrationService) error) *MockServiceHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceHandler creates a new instance of MockServiceHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceHandler {
	mock := &MockServiceHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
