// Code generated by mockery. DO NOT EDIT.

package mockrepository

import (
	context "context"

	entity "github.com/raoptimus/db-migrator.go/internal/dal/entity"
	mock "github.com/stretchr/testify/mock"
)

// adapter is an autogenerated mock type for the adapter type
type adapter struct {
	mock.Mock
}

type adapter_Expecter struct {
	mock *mock.Mock
}

func (_m *adapter) EXPECT() *adapter_Expecter {
	return &adapter_Expecter{mock: &_m.Mock}
}

// CreateMigrationHistoryTable provides a mock function with given fields: ctx
func (_m *adapter) CreateMigrationHistoryTable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateMigrationHistoryTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// adapter_CreateMigrationHistoryTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMigrationHistoryTable'
type adapter_CreateMigrationHistoryTable_Call struct {
	*mock.Call
}

// CreateMigrationHistoryTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *adapter_Expecter) CreateMigrationHistoryTable(ctx interface{}) *adapter_CreateMigrationHistoryTable_Call {
	return &adapter_CreateMigrationHistoryTable_Call{Call: _e.mock.On("CreateMigrationHistoryTable", ctx)}
}

func (_c *adapter_CreateMigrationHistoryTable_Call) Run(run func(ctx context.Context)) *adapter_CreateMigrationHistoryTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *adapter_CreateMigrationHistoryTable_Call) Return(_a0 error) *adapter_CreateMigrationHistoryTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_CreateMigrationHistoryTable_Call) RunAndReturn(run func(context.Context) error) *adapter_CreateMigrationHistoryTable_Call {
	_c.Call.Return(run)
	return _c
}

// DropMigrationHistoryTable provides a mock function with given fields: ctx
func (_m *adapter) DropMigrationHistoryTable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DropMigrationHistoryTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// adapter_DropMigrationHistoryTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropMigrationHistoryTable'
type adapter_DropMigrationHistoryTable_Call struct {
	*mock.Call
}

// DropMigrationHistoryTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *adapter_Expecter) DropMigrationHistoryTable(ctx interface{}) *adapter_DropMigrationHistoryTable_Call {
	return &adapter_DropMigrationHistoryTable_Call{Call: _e.mock.On("DropMigrationHistoryTable", ctx)}
}

func (_c *adapter_DropMigrationHistoryTable_Call) Run(run func(ctx context.Context)) *adapter_DropMigrationHistoryTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *adapter_DropMigrationHistoryTable_Call) Return(_a0 error) *adapter_DropMigrationHistoryTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_DropMigrationHistoryTable_Call) RunAndReturn(run func(context.Context) error) *adapter_DropMigrationHistoryTable_Call {
	_c.Call.Return(run)
	return _c
}

// ExecQuery provides a mock function with given fields: ctx, query, args
func (_m *adapter) ExecQuery(ctx context.Context, query string, args ...any) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// adapter_ExecQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecQuery'
type adapter_ExecQuery_Call struct {
	*mock.Call
}

// ExecQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *adapter_Expecter) ExecQuery(ctx interface{}, query interface{}, args ...interface{}) *adapter_ExecQuery_Call {
	return &adapter_ExecQuery_Call{Call: _e.mock.On("ExecQuery",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *adapter_ExecQuery_Call) Run(run func(ctx context.Context, query string, args ...any)) *adapter_ExecQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *adapter_ExecQuery_Call) Return(_a0 error) *adapter_ExecQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_ExecQuery_Call) RunAndReturn(run func(context.Context, string, ...any) error) *adapter_ExecQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ExecQueryTransaction provides a mock function with given fields: ctx, fnTx
func (_m *adapter) ExecQueryTransaction(ctx context.Context, fnTx func(context.Context) error) error {
	ret := _m.Called(ctx, fnTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecQueryTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fnTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// adapter_ExecQueryTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecQueryTransaction'
type adapter_ExecQueryTransaction_Call struct {
	*mock.Call
}

// ExecQueryTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fnTx func(context.Context) error
func (_e *adapter_Expecter) ExecQueryTransaction(ctx interface{}, fnTx interface{}) *adapter_ExecQueryTransaction_Call {
	return &adapter_ExecQueryTransaction_Call{Call: _e.mock.On("ExecQueryTransaction", ctx, fnTx)}
}

func (_c *adapter_ExecQueryTransaction_Call) Run(run func(ctx context.Context, fnTx func(context.Context) error)) *adapter_ExecQueryTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *adapter_ExecQueryTransaction_Call) Return(_a0 error) *adapter_ExecQueryTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_ExecQueryTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *adapter_ExecQueryTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsMigration provides a mock function with given fields: ctx, version
func (_m *adapter) ExistsMigration(ctx context.Context, version string) (bool, error) {
	ret := _m.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for ExistsMigration")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, version)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// adapter_ExistsMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsMigration'
type adapter_ExistsMigration_Call struct {
	*mock.Call
}

// ExistsMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *adapter_Expecter) ExistsMigration(ctx interface{}, version interface{}) *adapter_ExistsMigration_Call {
	return &adapter_ExistsMigration_Call{Call: _e.mock.On("ExistsMigration", ctx, version)}
}

func (_c *adapter_ExistsMigration_Call) Run(run func(ctx context.Context, version string)) *adapter_ExistsMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *adapter_ExistsMigration_Call) Return(_a0 bool, _a1 error) *adapter_ExistsMigration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *adapter_ExistsMigration_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *adapter_ExistsMigration_Call {
	_c.Call.Return(run)
	return _c
}

// ForceSafely provides a mock function with no fields
func (_m *adapter) ForceSafely() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ForceSafely")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// adapter_ForceSafely_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceSafely'
type adapter_ForceSafely_Call struct {
	*mock.Call
}

// ForceSafely is a helper method to define mock.On call
func (_e *adapter_Expecter) ForceSafely() *adapter_ForceSafely_Call {
	return &adapter_ForceSafely_Call{Call: _e.mock.On("ForceSafely")}
}

func (_c *adapter_ForceSafely_Call) Run(run func()) *adapter_ForceSafely_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *adapter_ForceSafely_Call) Return(_a0 bool) *adapter_ForceSafely_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_ForceSafely_Call) RunAndReturn(run func() bool) *adapter_ForceSafely_Call {
	_c.Call.Return(run)
	return _c
}

// HasMigrationHistoryTable provides a mock function with given fields: ctx
func (_m *adapter) HasMigrationHistoryTable(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HasMigrationHistoryTable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// adapter_HasMigrationHistoryTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasMigrationHistoryTable'
type adapter_HasMigrationHistoryTable_Call struct {
	*mock.Call
}

// HasMigrationHistoryTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *adapter_Expecter) HasMigrationHistoryTable(ctx interface{}) *adapter_HasMigrationHistoryTable_Call {
	return &adapter_HasMigrationHistoryTable_Call{Call: _e.mock.On("HasMigrationHistoryTable", ctx)}
}

func (_c *adapter_HasMigrationHistoryTable_Call) Run(run func(ctx context.Context)) *adapter_HasMigrationHistoryTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *adapter_HasMigrationHistoryTable_Call) Return(exists bool, err error) *adapter_HasMigrationHistoryTable_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *adapter_HasMigrationHistoryTable_Call) RunAndReturn(run func(context.Context) (bool, error)) *adapter_HasMigrationHistoryTable_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMigration provides a mock function with given fields: ctx, version
func (_m *adapter) InsertMigration(ctx context.Context, version string) error {
	ret := _m.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for InsertMigration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// adapter_InsertMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMigration'
type adapter_InsertMigration_Call struct {
	*mock.Call
}

// InsertMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *adapter_Expecter) InsertMigration(ctx interface{}, version interface{}) *adapter_InsertMigration_Call {
	return &adapter_InsertMigration_Call{Call: _e.mock.On("InsertMigration", ctx, version)}
}

func (_c *adapter_InsertMigration_Call) Run(run func(ctx context.Context, version string)) *adapter_InsertMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *adapter_InsertMigration_Call) Return(_a0 error) *adapter_InsertMigration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_InsertMigration_Call) RunAndReturn(run func(context.Context, string) error) *adapter_InsertMigration_Call {
	_c.Call.Return(run)
	return _c
}

// Migrations provides a mock function with given fields: ctx, limit
func (_m *adapter) Migrations(ctx context.Context, limit int) (entity.Migrations, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Migrations")
	}

	var r0 entity.Migrations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entity.Migrations, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entity.Migrations); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.Migrations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// adapter_Migrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrations'
type adapter_Migrations_Call struct {
	*mock.Call
}

// Migrations is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *adapter_Expecter) Migrations(ctx interface{}, limit interface{}) *adapter_Migrations_Call {
	return &adapter_Migrations_Call{Call: _e.mock.On("Migrations", ctx, limit)}
}

func (_c *adapter_Migrations_Call) Run(run func(ctx context.Context, limit int)) *adapter_Migrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *adapter_Migrations_Call) Return(_a0 entity.Migrations, _a1 error) *adapter_Migrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *adapter_Migrations_Call) RunAndReturn(run func(context.Context, int) (entity.Migrations, error)) *adapter_Migrations_Call {
	_c.Call.Return(run)
	return _c
}

// MigrationsCount provides a mock function with given fields: ctx
func (_m *adapter) MigrationsCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MigrationsCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// adapter_MigrationsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrationsCount'
type adapter_MigrationsCount_Call struct {
	*mock.Call
}

// MigrationsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *adapter_Expecter) MigrationsCount(ctx interface{}) *adapter_MigrationsCount_Call {
	return &adapter_MigrationsCount_Call{Call: _e.mock.On("MigrationsCount", ctx)}
}

func (_c *adapter_MigrationsCount_Call) Run(run func(ctx context.Context)) *adapter_MigrationsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *adapter_MigrationsCount_Call) Return(_a0 int, _a1 error) *adapter_MigrationsCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *adapter_MigrationsCount_Call) RunAndReturn(run func(context.Context) (int, error)) *adapter_MigrationsCount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMigration provides a mock function with given fields: ctx, version
func (_m *adapter) RemoveMigration(ctx context.Context, version string) error {
	ret := _m.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMigration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// adapter_RemoveMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMigration'
type adapter_RemoveMigration_Call struct {
	*mock.Call
}

// RemoveMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *adapter_Expecter) RemoveMigration(ctx interface{}, version interface{}) *adapter_RemoveMigration_Call {
	return &adapter_RemoveMigration_Call{Call: _e.mock.On("RemoveMigration", ctx, version)}
}

func (_c *adapter_RemoveMigration_Call) Run(run func(ctx context.Context, version string)) *adapter_RemoveMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *adapter_RemoveMigration_Call) Return(_a0 error) *adapter_RemoveMigration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_RemoveMigration_Call) RunAndReturn(run func(context.Context, string) error) *adapter_RemoveMigration_Call {
	_c.Call.Return(run)
	return _c
}

// TableNameWithSchema provides a mock function with no fields
func (_m *adapter) TableNameWithSchema() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableNameWithSchema")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// adapter_TableNameWithSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableNameWithSchema'
type adapter_TableNameWithSchema_Call struct {
	*mock.Call
}

// TableNameWithSchema is a helper method to define mock.On call
func (_e *adapter_Expecter) TableNameWithSchema() *adapter_TableNameWithSchema_Call {
	return &adapter_TableNameWithSchema_Call{Call: _e.mock.On("TableNameWithSchema")}
}

func (_c *adapter_TableNameWithSchema_Call) Run(run func()) *adapter_TableNameWithSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *adapter_TableNameWithSchema_Call) Return(_a0 string) *adapter_TableNameWithSchema_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *adapter_TableNameWithSchema_Call) RunAndReturn(run func() string) *adapter_TableNameWithSchema_Call {
	_c.Call.Return(run)
	return _c
}

// newAdapter creates a new instance of adapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *adapter {
	mock := &adapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
