// Code generated by mockery. DO NOT EDIT.

package service

import (
	context "context"

	entity "github.com/raoptimus/db-migrator.go/internal/infrastructure/dal/entity"
	mock "github.com/stretchr/testify/mock"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateMigrationHistoryTable provides a mock function with given fields: ctx
func (_m *MockRepository) CreateMigrationHistoryTable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CreateMigrationHistoryTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateMigrationHistoryTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMigrationHistoryTable'
type MockRepository_CreateMigrationHistoryTable_Call struct {
	*mock.Call
}

// CreateMigrationHistoryTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) CreateMigrationHistoryTable(ctx interface{}) *MockRepository_CreateMigrationHistoryTable_Call {
	return &MockRepository_CreateMigrationHistoryTable_Call{Call: _e.mock.On("CreateMigrationHistoryTable", ctx)}
}

func (_c *MockRepository_CreateMigrationHistoryTable_Call) Run(run func(ctx context.Context)) *MockRepository_CreateMigrationHistoryTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_CreateMigrationHistoryTable_Call) Return(_a0 error) *MockRepository_CreateMigrationHistoryTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateMigrationHistoryTable_Call) RunAndReturn(run func(context.Context) error) *MockRepository_CreateMigrationHistoryTable_Call {
	_c.Call.Return(run)
	return _c
}

// DropMigrationHistoryTable provides a mock function with given fields: ctx
func (_m *MockRepository) DropMigrationHistoryTable(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DropMigrationHistoryTable")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_DropMigrationHistoryTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DropMigrationHistoryTable'
type MockRepository_DropMigrationHistoryTable_Call struct {
	*mock.Call
}

// DropMigrationHistoryTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) DropMigrationHistoryTable(ctx interface{}) *MockRepository_DropMigrationHistoryTable_Call {
	return &MockRepository_DropMigrationHistoryTable_Call{Call: _e.mock.On("DropMigrationHistoryTable", ctx)}
}

func (_c *MockRepository_DropMigrationHistoryTable_Call) Run(run func(ctx context.Context)) *MockRepository_DropMigrationHistoryTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_DropMigrationHistoryTable_Call) Return(_a0 error) *MockRepository_DropMigrationHistoryTable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_DropMigrationHistoryTable_Call) RunAndReturn(run func(context.Context) error) *MockRepository_DropMigrationHistoryTable_Call {
	_c.Call.Return(run)
	return _c
}

// ExecQuery provides a mock function with given fields: ctx, query, args
func (_m *MockRepository) ExecQuery(ctx context.Context, query string, args ...any) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecQuery")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) error); ok {
		r0 = rf(ctx, query, args...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ExecQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecQuery'
type MockRepository_ExecQuery_Call struct {
	*mock.Call
}

// ExecQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockRepository_Expecter) ExecQuery(ctx interface{}, query interface{}, args ...interface{}) *MockRepository_ExecQuery_Call {
	return &MockRepository_ExecQuery_Call{Call: _e.mock.On("ExecQuery",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockRepository_ExecQuery_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockRepository_ExecQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockRepository_ExecQuery_Call) Return(_a0 error) *MockRepository_ExecQuery_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ExecQuery_Call) RunAndReturn(run func(context.Context, string, ...any) error) *MockRepository_ExecQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ExecQueryTransaction provides a mock function with given fields: ctx, fnTx
func (_m *MockRepository) ExecQueryTransaction(ctx context.Context, fnTx func(context.Context) error) error {
	ret := _m.Called(ctx, fnTx)

	if len(ret) == 0 {
		panic("no return value specified for ExecQueryTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fnTx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_ExecQueryTransaction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecQueryTransaction'
type MockRepository_ExecQueryTransaction_Call struct {
	*mock.Call
}

// ExecQueryTransaction is a helper method to define mock.On call
//   - ctx context.Context
//   - fnTx func(context.Context) error
func (_e *MockRepository_Expecter) ExecQueryTransaction(ctx interface{}, fnTx interface{}) *MockRepository_ExecQueryTransaction_Call {
	return &MockRepository_ExecQueryTransaction_Call{Call: _e.mock.On("ExecQueryTransaction", ctx, fnTx)}
}

func (_c *MockRepository_ExecQueryTransaction_Call) Run(run func(ctx context.Context, fnTx func(context.Context) error)) *MockRepository_ExecQueryTransaction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockRepository_ExecQueryTransaction_Call) Return(_a0 error) *MockRepository_ExecQueryTransaction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_ExecQueryTransaction_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockRepository_ExecQueryTransaction_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsMigration provides a mock function with given fields: ctx, version
func (_m *MockRepository) ExistsMigration(ctx context.Context, version string) (bool, error) {
	ret := _m.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for ExistsMigration")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, version)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ExistsMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsMigration'
type MockRepository_ExistsMigration_Call struct {
	*mock.Call
}

// ExistsMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockRepository_Expecter) ExistsMigration(ctx interface{}, version interface{}) *MockRepository_ExistsMigration_Call {
	return &MockRepository_ExistsMigration_Call{Call: _e.mock.On("ExistsMigration", ctx, version)}
}

func (_c *MockRepository_ExistsMigration_Call) Run(run func(ctx context.Context, version string)) *MockRepository_ExistsMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_ExistsMigration_Call) Return(_a0 bool, _a1 error) *MockRepository_ExistsMigration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ExistsMigration_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockRepository_ExistsMigration_Call {
	_c.Call.Return(run)
	return _c
}

// HasMigrationHistoryTable provides a mock function with given fields: ctx
func (_m *MockRepository) HasMigrationHistoryTable(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HasMigrationHistoryTable")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_HasMigrationHistoryTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasMigrationHistoryTable'
type MockRepository_HasMigrationHistoryTable_Call struct {
	*mock.Call
}

// HasMigrationHistoryTable is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) HasMigrationHistoryTable(ctx interface{}) *MockRepository_HasMigrationHistoryTable_Call {
	return &MockRepository_HasMigrationHistoryTable_Call{Call: _e.mock.On("HasMigrationHistoryTable", ctx)}
}

func (_c *MockRepository_HasMigrationHistoryTable_Call) Run(run func(ctx context.Context)) *MockRepository_HasMigrationHistoryTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_HasMigrationHistoryTable_Call) Return(exists bool, err error) *MockRepository_HasMigrationHistoryTable_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockRepository_HasMigrationHistoryTable_Call) RunAndReturn(run func(context.Context) (bool, error)) *MockRepository_HasMigrationHistoryTable_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMigration provides a mock function with given fields: ctx, version
func (_m *MockRepository) InsertMigration(ctx context.Context, version string) error {
	ret := _m.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for InsertMigration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_InsertMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMigration'
type MockRepository_InsertMigration_Call struct {
	*mock.Call
}

// InsertMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockRepository_Expecter) InsertMigration(ctx interface{}, version interface{}) *MockRepository_InsertMigration_Call {
	return &MockRepository_InsertMigration_Call{Call: _e.mock.On("InsertMigration", ctx, version)}
}

func (_c *MockRepository_InsertMigration_Call) Run(run func(ctx context.Context, version string)) *MockRepository_InsertMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_InsertMigration_Call) Return(_a0 error) *MockRepository_InsertMigration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_InsertMigration_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_InsertMigration_Call {
	_c.Call.Return(run)
	return _c
}

// Migrations provides a mock function with given fields: ctx, limit
func (_m *MockRepository) Migrations(ctx context.Context, limit int) (entity.Migrations, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for Migrations")
	}

	var r0 entity.Migrations
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (entity.Migrations, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) entity.Migrations); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(entity.Migrations)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_Migrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Migrations'
type MockRepository_Migrations_Call struct {
	*mock.Call
}

// Migrations is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockRepository_Expecter) Migrations(ctx interface{}, limit interface{}) *MockRepository_Migrations_Call {
	return &MockRepository_Migrations_Call{Call: _e.mock.On("Migrations", ctx, limit)}
}

func (_c *MockRepository_Migrations_Call) Run(run func(ctx context.Context, limit int)) *MockRepository_Migrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockRepository_Migrations_Call) Return(_a0 entity.Migrations, _a1 error) *MockRepository_Migrations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_Migrations_Call) RunAndReturn(run func(context.Context, int) (entity.Migrations, error)) *MockRepository_Migrations_Call {
	_c.Call.Return(run)
	return _c
}

// MigrationsCount provides a mock function with given fields: ctx
func (_m *MockRepository) MigrationsCount(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MigrationsCount")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_MigrationsCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MigrationsCount'
type MockRepository_MigrationsCount_Call struct {
	*mock.Call
}

// MigrationsCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRepository_Expecter) MigrationsCount(ctx interface{}) *MockRepository_MigrationsCount_Call {
	return &MockRepository_MigrationsCount_Call{Call: _e.mock.On("MigrationsCount", ctx)}
}

func (_c *MockRepository_MigrationsCount_Call) Run(run func(ctx context.Context)) *MockRepository_MigrationsCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockRepository_MigrationsCount_Call) Return(_a0 int, _a1 error) *MockRepository_MigrationsCount_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_MigrationsCount_Call) RunAndReturn(run func(context.Context) (int, error)) *MockRepository_MigrationsCount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMigration provides a mock function with given fields: ctx, version
func (_m *MockRepository) RemoveMigration(ctx context.Context, version string) error {
	ret := _m.Called(ctx, version)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMigration")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, version)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RemoveMigration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMigration'
type MockRepository_RemoveMigration_Call struct {
	*mock.Call
}

// RemoveMigration is a helper method to define mock.On call
//   - ctx context.Context
//   - version string
func (_e *MockRepository_Expecter) RemoveMigration(ctx interface{}, version interface{}) *MockRepository_RemoveMigration_Call {
	return &MockRepository_RemoveMigration_Call{Call: _e.mock.On("RemoveMigration", ctx, version)}
}

func (_c *MockRepository_RemoveMigration_Call) Run(run func(ctx context.Context, version string)) *MockRepository_RemoveMigration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockRepository_RemoveMigration_Call) Return(_a0 error) *MockRepository_RemoveMigration_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RemoveMigration_Call) RunAndReturn(run func(context.Context, string) error) *MockRepository_RemoveMigration_Call {
	_c.Call.Return(run)
	return _c
}

// TableNameWithSchema provides a mock function with no fields
func (_m *MockRepository) TableNameWithSchema() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableNameWithSchema")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRepository_TableNameWithSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableNameWithSchema'
type MockRepository_TableNameWithSchema_Call struct {
	*mock.Call
}

// TableNameWithSchema is a helper method to define mock.On call
func (_e *MockRepository_Expecter) TableNameWithSchema() *MockRepository_TableNameWithSchema_Call {
	return &MockRepository_TableNameWithSchema_Call{Call: _e.mock.On("TableNameWithSchema")}
}

func (_c *MockRepository_TableNameWithSchema_Call) Run(run func()) *MockRepository_TableNameWithSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRepository_TableNameWithSchema_Call) Return(_a0 string) *MockRepository_TableNameWithSchema_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_TableNameWithSchema_Call) RunAndReturn(run func() string) *MockRepository_TableNameWithSchema_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
