// Code generated by mockery. DO NOT EDIT.

package mockaction

import mock "github.com/stretchr/testify/mock"

// File is an autogenerated mock type for the File type
type File struct {
	mock.Mock
}

type File_Expecter struct {
	mock *mock.Mock
}

func (_m *File) EXPECT() *File_Expecter {
	return &File_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: filename
func (_m *File) Create(filename string) error {
	ret := _m.Called(filename)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(filename)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// File_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type File_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - filename string
func (_e *File_Expecter) Create(filename interface{}) *File_Create_Call {
	return &File_Create_Call{Call: _e.mock.On("Create", filename)}
}

func (_c *File_Create_Call) Run(run func(filename string)) *File_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *File_Create_Call) Return(_a0 error) *File_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *File_Create_Call) RunAndReturn(run func(string) error) *File_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: path
func (_m *File) Exists(path string) (bool, error) {
	ret := _m.Called(path)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// File_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type File_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - path string
func (_e *File_Expecter) Exists(path interface{}) *File_Exists_Call {
	return &File_Exists_Call{Call: _e.mock.On("Exists", path)}
}

func (_c *File_Exists_Call) Run(run func(path string)) *File_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *File_Exists_Call) Return(_a0 bool, _a1 error) *File_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *File_Exists_Call) RunAndReturn(run func(string) (bool, error)) *File_Exists_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFile interface {
	mock.TestingT
	Cleanup(func())
}

// NewFile creates a new instance of File. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFile(t mockConstructorTestingTNewFile) *File {
	mock := &File{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
