// Code generated by mockery. DO NOT EDIT.

package sqlex

import mock "github.com/stretchr/testify/mock"

// MockRows is an autogenerated mock type for the Rows type
type MockRows struct {
	mock.Mock
}

type MockRows_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRows) EXPECT() *MockRows_Expecter {
	return &MockRows_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockRows) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRows_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockRows_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockRows_Expecter) Close() *MockRows_Close_Call {
	return &MockRows_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockRows_Close_Call) Run(run func()) *MockRows_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRows_Close_Call) Return(_a0 error) *MockRows_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRows_Close_Call) RunAndReturn(run func() error) *MockRows_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Err provides a mock function with no fields
func (_m *MockRows) Err() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Err")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRows_Err_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Err'
type MockRows_Err_Call struct {
	*mock.Call
}

// Err is a helper method to define mock.On call
func (_e *MockRows_Expecter) Err() *MockRows_Err_Call {
	return &MockRows_Err_Call{Call: _e.mock.On("Err")}
}

func (_c *MockRows_Err_Call) Run(run func()) *MockRows_Err_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRows_Err_Call) Return(_a0 error) *MockRows_Err_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRows_Err_Call) RunAndReturn(run func() error) *MockRows_Err_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function with no fields
func (_m *MockRows) Next() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRows_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockRows_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockRows_Expecter) Next() *MockRows_Next_Call {
	return &MockRows_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockRows_Next_Call) Run(run func()) *MockRows_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRows_Next_Call) Return(_a0 bool) *MockRows_Next_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRows_Next_Call) RunAndReturn(run func() bool) *MockRows_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function with given fields: dest
func (_m *MockRows) Scan(dest ...any) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...any) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRows_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type MockRows_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - dest ...any
func (_e *MockRows_Expecter) Scan(dest ...interface{}) *MockRows_Scan_Call {
	return &MockRows_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{}, dest...)...)}
}

func (_c *MockRows_Scan_Call) Run(run func(dest ...any)) *MockRows_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-0)
		for i, a := range args[0:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(variadicArgs...)
	})
	return _c
}

func (_c *MockRows_Scan_Call) Return(_a0 error) *MockRows_Scan_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRows_Scan_Call) RunAndReturn(run func(...any) error) *MockRows_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRows creates a new instance of MockRows. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRows(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRows {
	mock := &MockRows{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
