// Code generated by mockery. DO NOT EDIT.

package sqlex

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStmt is an autogenerated mock type for the Stmt type
type MockStmt struct {
	mock.Mock
}

type MockStmt_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStmt) EXPECT() *MockStmt_Expecter {
	return &MockStmt_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function with given fields: ctx, args
func (_m *MockStmt) ExecContext(ctx context.Context, args ...any) (Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ...any) (Result, error)); ok {
		return rf(ctx, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ...any) Result); ok {
		r0 = rf(ctx, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ...any) error); ok {
		r1 = rf(ctx, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStmt_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockStmt_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - args ...any
func (_e *MockStmt_Expecter) ExecContext(ctx interface{}, args ...interface{}) *MockStmt_ExecContext_Call {
	return &MockStmt_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx}, args...)...)}
}

func (_c *MockStmt_ExecContext_Call) Run(run func(ctx context.Context, args ...any)) *MockStmt_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockStmt_ExecContext_Call) Return(_a0 Result, _a1 error) *MockStmt_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStmt_ExecContext_Call) RunAndReturn(run func(context.Context, ...any) (Result, error)) *MockStmt_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStmt creates a new instance of MockStmt. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStmt(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStmt {
	mock := &MockStmt{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
