// Code generated by mockery. DO NOT EDIT.

package connection

import mock "github.com/stretchr/testify/mock"

// MockDBPinger is an autogenerated mock type for the DBPinger type
type MockDBPinger struct {
	mock.Mock
}

type MockDBPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBPinger) EXPECT() *MockDBPinger_Expecter {
	return &MockDBPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with no fields
func (_m *MockDBPinger) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDBPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDBPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockDBPinger_Expecter) Ping() *MockDBPinger_Ping_Call {
	return &MockDBPinger_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockDBPinger_Ping_Call) Run(run func()) *MockDBPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDBPinger_Ping_Call) Return(_a0 error) *MockDBPinger_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDBPinger_Ping_Call) RunAndReturn(run func() error) *MockDBPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBPinger creates a new instance of MockDBPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBPinger {
	mock := &MockDBPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
