// Code generated by mockery. DO NOT EDIT.

package connection

import (
	context "context"

	sqlex "github.com/raoptimus/db-migrator.go/internal/infrastructure/sqlex"
	mock "github.com/stretchr/testify/mock"
)

// MockDBQuerier is an autogenerated mock type for the DBQuerier type
type MockDBQuerier struct {
	mock.Mock
}

type MockDBQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBQuerier) EXPECT() *MockDBQuerier_Expecter {
	return &MockDBQuerier_Expecter{mock: &_m.Mock}
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *MockDBQuerier) QueryContext(ctx context.Context, query string, args ...any) (sqlex.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 sqlex.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlex.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sqlex.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBQuerier_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockDBQuerier_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockDBQuerier_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockDBQuerier_QueryContext_Call {
	return &MockDBQuerier_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockDBQuerier_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockDBQuerier_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockDBQuerier_QueryContext_Call) Return(_a0 sqlex.Rows, _a1 error) *MockDBQuerier_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBQuerier_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sqlex.Rows, error)) *MockDBQuerier_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBQuerier creates a new instance of MockDBQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBQuerier {
	mock := &MockDBQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
