// Code generated by mockery. DO NOT EDIT.

package connection

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"

	sqlex "github.com/raoptimus/db-migrator.go/internal/infrastructure/sqlex"
)

// MockDBTransactor is an autogenerated mock type for the DBTransactor type
type MockDBTransactor struct {
	mock.Mock
}

type MockDBTransactor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBTransactor) EXPECT() *MockDBTransactor_Expecter {
	return &MockDBTransactor_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockDBTransactor) BeginTx(ctx context.Context, opts *sql.TxOptions) (sqlex.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 sqlex.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (sqlex.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) sqlex.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDBTransactor_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockDBTransactor_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockDBTransactor_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockDBTransactor_BeginTx_Call {
	return &MockDBTransactor_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockDBTransactor_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockDBTransactor_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockDBTransactor_BeginTx_Call) Return(_a0 sqlex.Tx, _a1 error) *MockDBTransactor_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDBTransactor_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (sqlex.Tx, error)) *MockDBTransactor_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBTransactor creates a new instance of MockDBTransactor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBTransactor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBTransactor {
	mock := &MockDBTransactor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
