// Code generated by mockery. DO NOT EDIT.

package connection

import (
	context "context"
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"

	sqlex "github.com/raoptimus/db-migrator.go/internal/infrastructure/sqlex"
)

// MockSQLDB is an autogenerated mock type for the SQLDB type
type MockSQLDB struct {
	mock.Mock
}

type MockSQLDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSQLDB) EXPECT() *MockSQLDB_Expecter {
	return &MockSQLDB_Expecter{mock: &_m.Mock}
}

// BeginTx provides a mock function with given fields: ctx, opts
func (_m *MockSQLDB) BeginTx(ctx context.Context, opts *sql.TxOptions) (sqlex.Tx, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 sqlex.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) (sqlex.Tx, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sql.TxOptions) sqlex.Tx); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sql.TxOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLDB_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type MockSQLDB_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *sql.TxOptions
func (_e *MockSQLDB_Expecter) BeginTx(ctx interface{}, opts interface{}) *MockSQLDB_BeginTx_Call {
	return &MockSQLDB_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, opts)}
}

func (_c *MockSQLDB_BeginTx_Call) Run(run func(ctx context.Context, opts *sql.TxOptions)) *MockSQLDB_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sql.TxOptions))
	})
	return _c
}

func (_c *MockSQLDB_BeginTx_Call) Return(_a0 sqlex.Tx, _a1 error) *MockSQLDB_BeginTx_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLDB_BeginTx_Call) RunAndReturn(run func(context.Context, *sql.TxOptions) (sqlex.Tx, error)) *MockSQLDB_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockSQLDB) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLDB_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSQLDB_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSQLDB_Expecter) Close() *MockSQLDB_Close_Call {
	return &MockSQLDB_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSQLDB_Close_Call) Run(run func()) *MockSQLDB_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSQLDB_Close_Call) Return(_a0 error) *MockSQLDB_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLDB_Close_Call) RunAndReturn(run func() error) *MockSQLDB_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *MockSQLDB) ExecContext(ctx context.Context, query string, args ...any) (sqlex.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sqlex.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlex.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sqlex.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLDB_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type MockSQLDB_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockSQLDB_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *MockSQLDB_ExecContext_Call {
	return &MockSQLDB_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockSQLDB_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockSQLDB_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSQLDB_ExecContext_Call) Return(_a0 sqlex.Result, _a1 error) *MockSQLDB_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLDB_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sqlex.Result, error)) *MockSQLDB_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with no fields
func (_m *MockSQLDB) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSQLDB_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockSQLDB_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *MockSQLDB_Expecter) Ping() *MockSQLDB_Ping_Call {
	return &MockSQLDB_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *MockSQLDB_Ping_Call) Run(run func()) *MockSQLDB_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSQLDB_Ping_Call) Return(_a0 error) *MockSQLDB_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSQLDB_Ping_Call) RunAndReturn(run func() error) *MockSQLDB_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// QueryContext provides a mock function with given fields: ctx, query, args
func (_m *MockSQLDB) QueryContext(ctx context.Context, query string, args ...any) (sqlex.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for QueryContext")
	}

	var r0 sqlex.Rows
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlex.Rows, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sqlex.Rows); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Rows)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSQLDB_QueryContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryContext'
type MockSQLDB_QueryContext_Call struct {
	*mock.Call
}

// QueryContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *MockSQLDB_Expecter) QueryContext(ctx interface{}, query interface{}, args ...interface{}) *MockSQLDB_QueryContext_Call {
	return &MockSQLDB_QueryContext_Call{Call: _e.mock.On("QueryContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *MockSQLDB_QueryContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *MockSQLDB_QueryContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockSQLDB_QueryContext_Call) Return(_a0 sqlex.Rows, _a1 error) *MockSQLDB_QueryContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSQLDB_QueryContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sqlex.Rows, error)) *MockSQLDB_QueryContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSQLDB creates a new instance of MockSQLDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSQLDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSQLDB {
	mock := &MockSQLDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
