// Code generated by mockery. DO NOT EDIT.

package mockconnection

import (
	context "context"

	sqlex "github.com/raoptimus/db-migrator.go/internal/sqlex"
	mock "github.com/stretchr/testify/mock"
)

// DBExecutor is an autogenerated mock type for the DBExecutor type
type DBExecutor struct {
	mock.Mock
}

type DBExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *DBExecutor) EXPECT() *DBExecutor_Expecter {
	return &DBExecutor_Expecter{mock: &_m.Mock}
}

// ExecContext provides a mock function with given fields: ctx, query, args
func (_m *DBExecutor) ExecContext(ctx context.Context, query string, args ...any) (sqlex.Result, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, query)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ExecContext")
	}

	var r0 sqlex.Result
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) (sqlex.Result, error)); ok {
		return rf(ctx, query, args...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, ...any) sqlex.Result); ok {
		r0 = rf(ctx, query, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sqlex.Result)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = rf(ctx, query, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DBExecutor_ExecContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContext'
type DBExecutor_ExecContext_Call struct {
	*mock.Call
}

// ExecContext is a helper method to define mock.On call
//   - ctx context.Context
//   - query string
//   - args ...any
func (_e *DBExecutor_Expecter) ExecContext(ctx interface{}, query interface{}, args ...interface{}) *DBExecutor_ExecContext_Call {
	return &DBExecutor_ExecContext_Call{Call: _e.mock.On("ExecContext",
		append([]interface{}{ctx, query}, args...)...)}
}

func (_c *DBExecutor_ExecContext_Call) Run(run func(ctx context.Context, query string, args ...any)) *DBExecutor_ExecContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]any, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(any)
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *DBExecutor_ExecContext_Call) Return(_a0 sqlex.Result, _a1 error) *DBExecutor_ExecContext_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DBExecutor_ExecContext_Call) RunAndReturn(run func(context.Context, string, ...any) (sqlex.Result, error)) *DBExecutor_ExecContext_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBExecutor creates a new instance of DBExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBExecutor {
	mock := &DBExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
