// Code generated by mockery. DO NOT EDIT.

package mockconnection

import mock "github.com/stretchr/testify/mock"

// DBPinger is an autogenerated mock type for the DBPinger type
type DBPinger struct {
	mock.Mock
}

type DBPinger_Expecter struct {
	mock *mock.Mock
}

func (_m *DBPinger) EXPECT() *DBPinger_Expecter {
	return &DBPinger_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function with no fields
func (_m *DBPinger) Ping() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DBPinger_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type DBPinger_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
func (_e *DBPinger_Expecter) Ping() *DBPinger_Ping_Call {
	return &DBPinger_Ping_Call{Call: _e.mock.On("Ping")}
}

func (_c *DBPinger_Ping_Call) Run(run func()) *DBPinger_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DBPinger_Ping_Call) Return(_a0 error) *DBPinger_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DBPinger_Ping_Call) RunAndReturn(run func() error) *DBPinger_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewDBPinger creates a new instance of DBPinger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDBPinger(t interface {
	mock.TestingT
	Cleanup(func())
}) *DBPinger {
	mock := &DBPinger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
