// Code generated by mockery. DO NOT EDIT.

package mockmockaction

import mock "github.com/stretchr/testify/mock"

// mockConstructorTestingTNewConsole is an autogenerated mock type for the mockConstructorTestingTNewConsole type
type mockConstructorTestingTNewConsole struct {
	mock.Mock
}

type mockConstructorTestingTNewConsole_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConstructorTestingTNewConsole) EXPECT() *mockConstructorTestingTNewConsole_Expecter {
	return &mockConstructorTestingTNewConsole_Expecter{mock: &_m.Mock}
}

// Cleanup provides a mock function with given fields: _a0
func (_m *mockConstructorTestingTNewConsole) Cleanup(_a0 func()) {
	_m.Called(_a0)
}

// mockConstructorTestingTNewConsole_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type mockConstructorTestingTNewConsole_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - _a0 func()
func (_e *mockConstructorTestingTNewConsole_Expecter) Cleanup(_a0 interface{}) *mockConstructorTestingTNewConsole_Cleanup_Call {
	return &mockConstructorTestingTNewConsole_Cleanup_Call{Call: _e.mock.On("Cleanup", _a0)}
}

func (_c *mockConstructorTestingTNewConsole_Cleanup_Call) Run(run func(_a0 func())) *mockConstructorTestingTNewConsole_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func()))
	})
	return _c
}

func (_c *mockConstructorTestingTNewConsole_Cleanup_Call) Return() *mockConstructorTestingTNewConsole_Cleanup_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewConsole_Cleanup_Call) RunAndReturn(run func(func())) *mockConstructorTestingTNewConsole_Cleanup_Call {
	_c.Run(run)
	return _c
}

// Errorf provides a mock function with given fields: format, args
func (_m *mockConstructorTestingTNewConsole) Errorf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// mockConstructorTestingTNewConsole_Errorf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Errorf'
type mockConstructorTestingTNewConsole_Errorf_Call struct {
	*mock.Call
}

// Errorf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *mockConstructorTestingTNewConsole_Expecter) Errorf(format interface{}, args ...interface{}) *mockConstructorTestingTNewConsole_Errorf_Call {
	return &mockConstructorTestingTNewConsole_Errorf_Call{Call: _e.mock.On("Errorf",
		append([]interface{}{format}, args...)...)}
}

func (_c *mockConstructorTestingTNewConsole_Errorf_Call) Run(run func(format string, args ...interface{})) *mockConstructorTestingTNewConsole_Errorf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockConstructorTestingTNewConsole_Errorf_Call) Return() *mockConstructorTestingTNewConsole_Errorf_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewConsole_Errorf_Call) RunAndReturn(run func(string, ...interface{})) *mockConstructorTestingTNewConsole_Errorf_Call {
	_c.Run(run)
	return _c
}

// FailNow provides a mock function with no fields
func (_m *mockConstructorTestingTNewConsole) FailNow() {
	_m.Called()
}

// mockConstructorTestingTNewConsole_FailNow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailNow'
type mockConstructorTestingTNewConsole_FailNow_Call struct {
	*mock.Call
}

// FailNow is a helper method to define mock.On call
func (_e *mockConstructorTestingTNewConsole_Expecter) FailNow() *mockConstructorTestingTNewConsole_FailNow_Call {
	return &mockConstructorTestingTNewConsole_FailNow_Call{Call: _e.mock.On("FailNow")}
}

func (_c *mockConstructorTestingTNewConsole_FailNow_Call) Run(run func()) *mockConstructorTestingTNewConsole_FailNow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockConstructorTestingTNewConsole_FailNow_Call) Return() *mockConstructorTestingTNewConsole_FailNow_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewConsole_FailNow_Call) RunAndReturn(run func()) *mockConstructorTestingTNewConsole_FailNow_Call {
	_c.Run(run)
	return _c
}

// Logf provides a mock function with given fields: format, args
func (_m *mockConstructorTestingTNewConsole) Logf(format string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, format)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// mockConstructorTestingTNewConsole_Logf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logf'
type mockConstructorTestingTNewConsole_Logf_Call struct {
	*mock.Call
}

// Logf is a helper method to define mock.On call
//   - format string
//   - args ...interface{}
func (_e *mockConstructorTestingTNewConsole_Expecter) Logf(format interface{}, args ...interface{}) *mockConstructorTestingTNewConsole_Logf_Call {
	return &mockConstructorTestingTNewConsole_Logf_Call{Call: _e.mock.On("Logf",
		append([]interface{}{format}, args...)...)}
}

func (_c *mockConstructorTestingTNewConsole_Logf_Call) Run(run func(format string, args ...interface{})) *mockConstructorTestingTNewConsole_Logf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *mockConstructorTestingTNewConsole_Logf_Call) Return() *mockConstructorTestingTNewConsole_Logf_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockConstructorTestingTNewConsole_Logf_Call) RunAndReturn(run func(string, ...interface{})) *mockConstructorTestingTNewConsole_Logf_Call {
	_c.Run(run)
	return _c
}

// newMockConstructorTestingTNewConsole creates a new instance of mockConstructorTestingTNewConsole. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConstructorTestingTNewConsole(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConstructorTestingTNewConsole {
	mock := &mockConstructorTestingTNewConsole{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
